### ISSUE TITLE
ipfs object patch not supported

### ISSUE THREAD

**Issue by bergie** [ipfs/js-ipfs-api#101]
Looking at the [ipfs object methods](https://github.com/ipfs/js-ipfs-api/blob/master/src/index.js#L126), it seems that `ipfs object patch` is not supported.

This would be super-useful for partial updates to IPFS hashes.

**Comment by diasdavid** [comment]
Hey @bergie, @haadcode PR'ed this yesterday on https://github.com/ipfs/js-ipfs-api/pull/103

Please make sure to send a hi5 :)
