### ISSUE TITLE
dist/{ipfsapi.js, ipfsapi.min.js} not actually compiled

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/js-ipfs-api#113]
The files `dist/ipfsapi.min.js` and `dist/ipfsapi.js` are not containing the libraries code anymore, since commit f6a7da682f205b13424dfd6082f3eaae51af7a73. The only thing I can see in the files is the standard browserify code, without anything about ipfs. Seems like we're missing to source the correct files in the build-step.

**Comment by VictorBjelkholm** [comment]
ping @Dignifiedquire (last commit on files)

**Comment by Dignifiedquire** [comment]
😓

**Comment by Dignifiedquire** [comment]
one of the reasons why I hate having compiled files checked into git..

**Comment by VictorBjelkholm** [comment]
Agreed, if possible, we should not have built files into scm. As @Dignifiedquire mentioned in IRC, we can make use of https://npmcdn.com/ that allows us to include the `dist/` folder in our published package but not in the scm. To me making use of that makes sense.

**Comment by diasdavid** [comment]
done https://github.com/ipfs/js-ipfs-api/releases/tag/v2.7.3 :)
