### ISSUE TITLE
Problem with [ ] characters in path

### ISSUE THREAD

**Issue by nycoliver** [ipfs/js-ipfs-api#114]
Adding a file at a path that contains open and close square brackets doesn't work. No error, but the response name is blank and the hash points to an empty directory.

Steps to reproduce:

    ipfs.add('[TEST]/test.txt', function(err, res) {
        console.log(err, res);
    })

I'm expecting this response:

    [ { Name: 'text.txt',
    Hash: 'Qmazm4yVXBrbJfLsscsNdTUwZ6yFMfjNoV26vKHMyjm9qw' } ]

but get this instead:

    [ { Name: '',
    Hash: 'QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn' } ]

which points to an empty directory.

**Comment by diasdavid** [comment]
@ikeafurniture, thank you for reporting, seems that it escaped our testing, could you submit a PR with a failing test?

**Comment by jbenet** [comment]
Huh, that's very odd!

Is this a js or go-ipfs thing?

**Comment by Mithgol** [comment]
I've just tried `ipfs add [foo]/bar.txt` on Windows and got `added QmQZB43ePCwDsow74gehT8v74M2tKtTs9FCbH4wpoUksfF bar.txt` from go-ipfs.

So, even if it's go-ipfs thing, it's not a CLI thing. Must be either go-ipfs API implementation or js-ipfs-api.

**Comment by diasdavid** [comment]
@nycoliver have you had the chance to look into this again?

**Comment by diasdavid** [comment]
@nycoliver @Mithgol is this still an issue? Could you verify? If possible create a test making it fail. Thank you

**Comment by nycoliver** [comment]
Hi seems to be working now! Think this issue can be closed.

**Comment by diasdavid** [comment]
Thank you:)
