### ISSUE TITLE
Use of const in strict mode

### ISSUE THREAD

**Issue by aakilfernandes** [ipfs/js-ipfs-api#117]
SyntaxError: /Users/aakilfernandes/projects/safemarket/grunt-ipfs/node_modules/ipfs-api/src/request-api.js:3
    const request = require('request')
    ^^^^^
    Use of const in strict mode.

using 0.12.7

**Comment by Dignifiedquire** [comment]
Sorry js-ipfs-api is only compatible with nodejs>=4.0 as indicated in the engine field in package.json.

**Comment by aakilfernandes** [comment]
got it.
