### ISSUE TITLE
window.ipfsApi undefined in browser

### ISSUE THREAD

**Issue by ckeenan** [ipfs/js-ipfs-api#119]
Re docs: 
> Make the ipfsapi.min.js available through your server and load it using a normal \<script\> tag, this will export the ipfsAPI constructor on the window object, such that...

However, I am seeing `console.log(window.ipfsAPI)    // undefined`

Is documentation up to date for in-browser usage? I am trying to test out https://github.com/ipfs/js-ipfs-api/issues/55#issuecomment-136934361

**Comment by Dignifiedquire** [comment]
Thanks for the report, looks like we are missing the proper export setting in browserify to export as a global.
