### ISSUE TITLE
Firefox is concatenating two chunks (use case, PING)

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs-api#135]
https://gist.github.com/Dignifiedquire/e0ce1cc876fae511ea73/raw/d5fabcca5004de459631dd814eb78634d86a720f/gistfile1.md

@whyrusleeping why does PING need to be _chunked_? Shouldn't it be a ndjson _stream_ only? 

It is failing on Firefox because go-ipfs is sending something that is `application/json`. Chrome works fine for this case though

**Comment by jbenet** [comment]
i think a lot of these questions are based on what the golang http lib does. i think the chunked stuff happens automatically around everything else? not sure

**Comment by whyrusleeping** [comment]
this should be fixed now. ndjson should be correctly one object per line
