### ISSUE TITLE
constructor should take non-scheme specific urls

### ISSUE THREAD

**Issue by jbenet** [ipfs/js-ipfs-api#139]
this should work:

``` js
var ipfs = ipfsAPI("//localhost:5001")
```

**Comment by diasdavid** [comment]
Work happening at https://github.com/ipfs/js-ipfs-api/pull/664

**Comment by diasdavid** [comment]
https://github.com/ipfs/js-ipfs-api/pull/664#issuecomment-360982038 //cc @lgierth @hacdias
