### ISSUE TITLE
ipfs add url wrap doesn't work

### ISSUE THREAD

**Issue by jbenet** [ipfs/js-ipfs-api#140]
Expected:

``` js
ipfs.add(url, {wrap: true}, cb)
```

 would be equivalent to cli's `ipfs add -w`, preserving the last pathname.

**Comment by Dignifiedquire** [comment]
The main thing to do here is extracting the filename from a given url and passing it as a parameter.

**Comment by fazo96** [comment]
@Dignifiedquire something like this?

```javascript
var s = url.split('#')[0].split('/')
filename = s[name.length - 1].trim()
if(filename.length === 0) filename = 'index.html'
```

**Comment by Dignifiedquire** [comment]
@fazo96 yes, and then pass it like this `{content: res, path: filename}` to the `send` method (also need to add a test to check that this actually works)

**Comment by Dignifiedquire** [comment]
Or you could look into using https://nodejs.org/docs/latest/api/url.html

**Comment by Mithgol** [comment]
`require('path').basename( require('url').parse(yourURL).pathname )`

**Comment by diasdavid** [comment]
We have https://github.com/ipfs/js-ipfs-api#add-a-file-from-a-url-to-ipfs and tests https://github.com/ipfs/js-ipfs-api/blob/master/test/ipfs-api/util.spec.js#L73-L86, I'll call this done unless someone is still hitting a issue, let me know and we will reopen and check again.  Bonus if you provide a test case :D

**Comment by Mithgol** [comment]
Wait, does the API has anything equivalent to `ipfs add -w` that actually wraps? (Except `ipfs.util.addFromFs` of the parent directory, I mean.)

**Comment by hacdias** [comment]
@diasdavid is this issue still valid? As far as I know, the `wrap` option is called `wrapWithDirectory` and it actually works:

```javascript
const ipfsAPI = require('.')
const ipfs = ipfsAPI('/ip4/127.0.0.1/tcp/5001')

ipfs.util.addFromURL('https://hacdias.com/downloads/aprenda_a_programar.pdf', {wrapWithDirectory: true}, (err, result) => {
  console.log(result)
})
```

Prints:

```
[ { path: 'QmWisvrzmUhFr8Ab8WFVq7iVwskqkmesjB42JBd1AA1ZBX',
    hash: 'QmWisvrzmUhFr8Ab8WFVq7iVwskqkmesjB42JBd1AA1ZBX',
    size: 943569 },
  { path: '',
    hash: 'QmQXoUuuPPnBaVuwEKf3jhZvfFVbWLwjeBSiip58oW9QsB',
    size: 943663 } ]
```
