### ISSUE TITLE
ipfs object patch api clunky?

### ISSUE THREAD

**Issue by jbenet** [ipfs/js-ipfs-api#141]
i would expect either:

```js
ipfs.object.patch(root, 'add-link', name, hash, cb)
ipfs.object.patch([root, 'add-link', name, hash], cb)

// but not (current)
ipfs.object.patch(root, ['add-link', name, hash], cb)
```

**Comment by Dignifiedquire** [comment]
I think it should be the first one `ipfs.object.patch(root, 'add-link', name, hash, cb)`

**Comment by diasdavid** [comment]
Let's get that core spec done :)

**Comment by diasdavid** [comment]
@jbenet well, you know... https://github.com/ipfs/js-ipfs/issues/110 :D

**Comment by diasdavid** [comment]
Now, interface-ipfs-core and the Object API spec exists. The implementation on js-ipfs-api updated to conform with it. 

It shouldn't be 'clunky' anymore. Closing this issue, feedback is welcome on the interface-ipfs-core repo, see the API here:

https://github.com/ipfs/interface-ipfs-core/tree/master/API/object
