### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs-api#143]
We should add a changelog (and auto generated if possible on releases, though this depends on us having a decent commit message convention and enforcing it)

https://github.com/ajoslin/conventional-changelog

Discuss :)

**Comment by fazo96** [comment]
I think the most important thing is clear commit messages, also I see there is a little amount of commits between releases, so I don't think generating a changelog is very useful

**Comment by Mithgol** [comment]
I've encountered a necessity of a changelog. Today I am not sure why version 4.0.0 is a major version (in other words, what are the backwards-incompatible changes in it).

**Comment by diasdavid** [comment]
It were changes on the Object API that now follows the spec defined on https://github.com/ipfs/interface-ipfs-core#object, you should be able to use almost as you were using, with the different that you now have to call on the return object (the dagNode), .toJSON() to get a JSON format of the results (which will bring more info than sometimes just the Hash)

Agree on having a changelog 👍

**Comment by Mithgol** [comment]
I've encountered a necessity of a changelog.

Once again.

This time it took the form of `TypeError: IPFSAPI(...).add is not a function`.

**Comment by diasdavid** [comment]
Apologies @Mithgol, didn't want to cause any pain migrating. We created a (probably too small) entry on https://github.com/ipfs/js-ipfs-api/releases/tag/v5.0.0.

However, I'm surprised that `.add` stopped being a function as we created aliases here https://github.com/ipfs/js-ipfs-api/blob/master/src/load-commands.js#L32-L34. 

What version are you running?

**Comment by Mithgol** [comment]
I've tried version 5.0.1, but the problem seems to persist in version 6.0.1 as well.

Here's a screenshot for 6.0.1:

![(screenshot)](https://cloud.githubusercontent.com/assets/1088720/15870088/c01eb1cc-2cf7-11e6-81e5-96aa1b44b7a3.gif)

**Comment by Mithgol** [comment]
Here's a screenshot of the same method working in v4.1.0:

![(screenshot)](https://cloud.githubusercontent.com/assets/1088720/15870816/4ba34dbe-2cfa-11e6-90f4-8cc63f2db4d7.gif)

(Not very clean because I forgot to require the module from the start. But anyway.)

**Comment by dignifiedquire** [comment]
We will be doing this together with https://github.com/dignifiedquire/aegir/issues/30

**Comment by diasdavid** [comment]
In addition to the (soon to be) changelog, we now have:

- https://github.com/ipfs/interface-ipfs-core/issues/55

And are working towards making this experience less painful on: https://github.com/ipfs/http-api-spec/issues/116

**Comment by diasdavid** [comment]
We have changelogs now :D https://github.com/ipfs/js-ipfs-api/releases \o/

**Comment by Mithgol** [comment]
Excellent. Thanks.
