### ISSUE TITLE
Partial downloads (streaming?)

### ISSUE THREAD

**Issue by harlantwood** [ipfs/js-ipfs-api#149]
As a user of the API module, I'd like to download the first 5KB or so of a text file in ipfs, to generate a preview.  Can I do this, without downloading the whole file?

**Comment by harlantwood** [comment]
@jacksenechal

**Comment by Dignifiedquire** [comment]
As soon as we have proper header detection (https://github.com/ipfs/go-ipfs/pull/1979) `cat` will stream. But there is no way to abort requests in the browser (https://github.com/whatwg/fetch/issues/27) so effectively you will always pull down the whole file, unless go-ipfs directly adds a method for just requesting a partial file.

**Comment by diasdavid** [comment]
AFAIK, cat is streaming now, right?

**Comment by dignifiedquire** [comment]
pretty sure it does yes

**Comment by diasdavid** [comment]
@harlantwood You might want to confirm with your use case. Let us know if you hit any roadblock.

**Comment by diasdavid** [comment]
As @dignifiedquire mentioned, you are always able to get the first block (256KiB) through a object.get or block.get request, but that would be that you would implement your how mechanism to fetch. Does that suit you, @harlantwood ?

**Comment by harlantwood** [comment]
Great, I'll close this for now.  When I get back to using this directly again, I'll check the progress and reopen if necessary.  

Thanks for the work and progress on this.
