### ISSUE TITLE
Improve description of this module in the readme

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs-api#152]
Ref https://github.com/ipfs/js-ipfs-api/issues/151#issuecomment-159673813 for context

**Comment by diasdavid** [comment]
What else do we want to add to the readme? Could you itemsize please?

**Comment by RichardLitt** [comment]
- [ ] Contribute section
- [ ] License section
- [ ] Contribute to IPFS! Banner

**Comment by diasdavid** [comment]
Sounds good :) @RichardLitt, Master of All Docs, wanna PR that? :D

**Comment by diasdavid** [comment]
done in #268 , thank you @RichardLitt :)
