### ISSUE TITLE
Broken if not loaded using webpack due to `require.context`

### ISSUE THREAD

**Issue by alexmingoia** [ipfs/js-ipfs-api#159]
[require.context](https://github.com/ipfs/js-ipfs-api/blob/master/src/load-commands.js#L9) is not available unless transpiled using webpack. This breaks any module that depends on ipfs-api and uses another loader such as browserify, such as webui.

**Comment by Dignifiedquire** [comment]
If you don't want to transpile using webpack, why not just load the prebuilt files in `dist`?

**Comment by diasdavid** [comment]
@Dignifiedquire being browserify compatible, or in another words, maintaining that available for the developers that have been using js-ipfs-api with browserify from the beginning, it is kind of important and nice to have.

Seems like @alexmingoia already fixed it https://github.com/ipfs/js-ipfs-api/pull/160
