### ISSUE TITLE
Not being able to publish a minor update with `gulp release`

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs-api#171]
It might be my lack of understanding on how our [gulp-load-plugins](https://www.npmjs.com/package/gulp-load-plugins) setup works, but trying `MINOR=true gulp release` and `gulp release minor` and both didn't do what I expected, which was, to do all the process and release a minor version of this package.

How can I flip this booleans: https://github.com/ipfs/js-ipfs-api/blob/master/tasks/release.js#L32-L33 ?

**Comment by ralphtheninja** [comment]
You could also add a seam like:

```js
function getType () {
  if (process.env.RELEASE) return process.env.RELEASE

  if ($.util.env.major) return 'major'
  if ($.util.env.minor) return 'minor'

  return 'patch'
}
```

And do:

```
$ RELEASE=major gulp release
$ RELEASE=minor gulp release
$ RELEASE=patch gulp release
```

**Comment by Dignifiedquire** [comment]
These are cli flags, so a minor release is gulp release --minor and a major would be gulp release --major

**Comment by Dignifiedquire** [comment]
Also documented at the bottom of https://github.com/ipfs/js-ipfs-api/blob/master/CONTRIBUTING.md

**Comment by ralphtheninja** [comment]
That would also allow you to support things like `premajor`, `preminor` etc

```
$ npm version --help
npm version [<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease]
```

**Comment by Dignifiedquire** [comment]
I like cli flags because they work eveywhere, which env variables tend to not or at least not with the same syntax

**Comment by ralphtheninja** [comment]
> I like cli flags because they work eveywhere, which env variables tend to not or at least not with the same syntax

I agree and I also like cli flags. That said, sometimes you don't need to run it everywhere, e.g. building something might be fine to require *nix. There's also abstractions to help you with this and since I both like env vars and cli flags I obviously use [`rc`](https://github.com/dominictarr/rc) :)

**Comment by ralphtheninja** [comment]
@diasdavid Sorry. It wasn't my intention to turn this into a debate/bikeshed about env vars vs cli arguments :)

**Comment by Dignifiedquire** [comment]
@ralphtheninja well it's his fault for not readong all the nice docs I wrote for him :P

**Comment by diasdavid** [comment]
ahaha shame on me, I was fighting with `gulp release minor` and not understanding why I was getting an error. Thank you for writing nice docs, @Dignifiedquire :):)

**Comment by Dignifiedquire** [comment]
@diasdavid :laughing: no worries we all know nobody reads the docs :rocket:

**Comment by diasdavid** [comment]
To be fair, I actually read searched the README because I assumed you had written it somewhere, I was just not expecting that the releasing guide was on CONTRIBUTING.md, but now it makes sense :)
