### ISSUE TITLE
ipfs.resolve (or ipfs.path.resolve) is missing

### ISSUE THREAD

**Issue by fazo96** [ipfs/js-ipfs-api#174]
Maybe I haven't looked hard enough but I think `ipfs.path.resolve` or `ipfs.resolve` should be there (to solve relative paths like `/ipfs/<hash>/a/b/c` to `/ipfs/<hash>`).

If I have time later I can try adding it (with tests).

**Comment by diasdavid** [comment]
That is actually unixfs utilities, not part of the HTTP api itself. Nevertheless, it would be really nice to have a Node.js module that understands unixfs and it is able to resolve paths

**Comment by fazo96** [comment]
Uhm, I guess I could work around resolving paths by running `ls` on the second last then picking the hash corresponding to the last path segment.

**Comment by dignifiedquire** [comment]
I does not look like `ipfs path resolve` is a command. Do we still want to do this, and if so what exactly is the goal here?

**Comment by diasdavid** [comment]
I believe that @fazo96 is looking for something similar to `ipfs files stat /a/b/c` but that supports ipfs hashes instead of mfs paths.

**Comment by diasdavid** [comment]
Ok, rereading this issue, you can totally do `ipfs.files.cat` or `ipfs.files.get` on a path. You can't do `ipfs.object.get(path)` as the object api doesn't have any resolver function.

### however, the new DAG API (which comes to replace object) does and it is a WIP here: https://github.com/ipfs/interface-ipfs-core/pull/99 please share your review and thoughts in how it should work there.
