### ISSUE TITLE
[0.4.1] Handle the hidden option on add files

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs-api#181]

**Comment by diasdavid** [comment]
The hidden option?

**Comment by Dignifiedquire** [comment]
There is an option `hidden` that changes the way how hidden files (aka dotfiles) are handled when doing a recursive add

**Comment by diasdavid** [comment]
This is there now - https://github.com/ipfs/js-ipfs-api#add-files-or-entire-directories-from-the-filesystem-to-ipfs
