### ISSUE TITLE
Auto set json flag on config.set

### ISSUE THREAD

**Issue by xicombd** [ipfs/js-ipfs-api#219]
Currently you can't call [`config.set`](https://github.com/ipfs/js-ipfs-api/blob/master/src/api/config.js#L8-L14) with an object as the `value`. You need to `JSON.stringify` it and pass `{ json: true }` on the `opts`.

I suggest that we check the type of the `value`, `JSON.stringify` it if it's an `object` set the `opts` automatically if none were provided.

Let me know what you think, I would be happy to PR this :)

**Comment by dignifiedquire** [comment]
Yes please!
