### ISSUE TITLE
Problem installing with npm on Ubuntu

### ISSUE THREAD

**Issue by mlbk0** [ipfs/js-ipfs-api#229]
This is my first ever issue written, apologies if this is not the right place/way.

I have a strange bug when trying to install `ipfs-api` with `npm`.

I'm on Ubuntu 14.04.4 LTS. I have npm version 3.8.2.

When I run `npm install ipfs-api --save`, it installs successfully, albeit with two warnings
```
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
```

adding the dependency `"ipfs-api": "^2.13.2"` to my `package.json`.

But if I now delete the `node_modules/` directory and run `npm install` again, I get an error!

Here the error message:
```
npm WARN app@1.0.0 No repository field.
npm ERR! Linux 3.13.0-79-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v5.8.0
npm ERR! npm  v3.8.2
npm ERR! path censored/node_modules/esprima/bin/esparse.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'censored/node_modules/esprima/bin/esparse.js'
npm ERR! enoent ENOENT: no such file or directory, chmod 'censored/node_modules/esprima/bin/esparse.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     censored/npm-debug.log
```

**Comment by dignifiedquire** [comment]
That's an npm bug I'm afraid :( https://github.com/npm/npm/search?utf8=%E2%9C%93&q=ENOENT&type=Issues

**Comment by diasdavid** [comment]
@mlbk0 did you managed to get your issue fixed? Since it is an npm issue, feel welcome to jump on IRC for quick help so that you get unblocked :)

**Comment by RichardLitt** [comment]
Reopen as needed, if you don't have IRC!
