### ISSUE TITLE
Response length from ipfs add recursive

### ISSUE THREAD

**Issue by mariusdarila** [ipfs/js-ipfs-api#250]
Adding a folder from js-ipfs api returns just the list of files inside that folder(n). Adding a folder from ipfs api directly with `ipfs add -r ` returns also the hash for the root folder(n+1). This is a great feature because i can access files directly under root hash by name.

**Comment by diasdavid** [comment]
Could you post the snippet of code you are using to add those files? I'm asking this because if used with the `recursive` option set to `true`, the behaviour is expected to be the same (https://github.com/ipfs/js-ipfs-api/blob/master/test/api/add.spec.js#L86)

**Comment by mariusdarila** [comment]
Hello, this happens when I use go-ipfs 0.3.11 with latest js-ipfs-api version. Upgrading to ipfs 0.4 solves this :)

**Comment by diasdavid** [comment]
Awesome, that sounds about right, js-ipfs-api latest is only compatible with IPFS 0.4 and above. Closing then :)
