### ISSUE TITLE
implement `get`

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs-api#263]
Currently, js-ipfs-api doesn't have `get` implemented. We will be needing it for js-ipfs

//cc @voxelot

**Comment by xicombd** [comment]
Started having a look at this, but couldn't figure out what `0000644000000000000000000000001412655500300016646 0ustar0000000000000000` means on the [HTTP response](https://github.com/ipfs/http-api-spec/blob/master/apiary.apib#L6398) 😟 

Do you have any idea what this could be @diasdavid @RichardLitt?

**Comment by diasdavid** [comment]
I believe that is a serialized protobuf of a MerkleDAG Node https://github.com/vijayee/js-ipfs-merkle-dag/blob/master/src/dag-node.js#L171

**Comment by nginnever** [comment]
hey @xicombd! I am also working on this and was wondering the same thing. 

I think it has to do with tar compression. Looking into it more now.

**Comment by RichardLitt** [comment]
It is a .tar file, and should be returned with `application/x-tar` header. See https://github.com/ipfs/go-ipfs/issues/1824.

**Comment by nginnever** [comment]
Added the ideas here to <a href="https://github.com/ipfs/js-ipfs-api/pull/271"> PR 271</a>

**Comment by diasdavid** [comment]
Done in https://github.com/ipfs/js-ipfs-api/pull/337 \o/ :D
