### ISSUE TITLE
`Error: Cannot find module 'bl'`

### ISSUE THREAD

**Issue by Mithgol** [ipfs/js-ipfs-api#275]
The line `const bl = require('bl')` (added to `src/api/object.js` in 2000d220ddf9e6b2f72920cd207ae25a77fc3a3a) seems to cause an error because the package [`bl`](https://www.npmjs.com/package/bl) is not listed in the module's dependencies.

![(screenshot)](https://cloud.githubusercontent.com/assets/1088720/15327484/4b485720-1c5a-11e6-9df7-28be43e72f8b.png)

**Comment by dignifiedquire** [comment]
Yes looks like it's missing from the devDependencies

**Comment by Mithgol** [comment]
Wait, why `devDependencies` and not `dependencies`?

**Comment by diasdavid** [comment]
@Mithgol you are right, it should be on dependencies. Mind making a PR?

In the other hand, you are running IPFS and using the JS libs on Windows? That is awesome! How has been the experience so far?

**Comment by dignifiedquire** [comment]
my mistake, I misread the diff and thought it was inside a test

**Comment by Mithgol** [comment]
A pull request (#276) is made.

**Comment by Mithgol** [comment]
@diasdavid Yes, I'm running IPFS and using this JS API on Windows. Generally everything's fine there unless a minor issue surfaces such as this one or ipfs/go-ipfs#2642.

**Comment by diasdavid** [comment]
released 4.0.3 :)

**Comment by Mithgol** [comment]
After a bit of testing I can confirm that the above mentioned error is indeed eliminated in the version 4.0.3.
