### ISSUE TITLE
API Proposal: refactor file adding

### ISSUE THREAD

**Issue by noffle** [ipfs/js-ipfs-api#279]
## Background

We're in the process of unifying the [js-ipfs](https://github.com/ipfs/js-ipfs) and js-ipfs-api APIs to be consistent, provided by the [interface-ipfs-core](https://github.com/ipfs/interface-ipfs-core) interface. For the roadmap, see [this](https://github.com/ipfs/interface-ipfs-core/issues/18) issue.

Part of this process is identifying what API calls from js-ipfs-api should be part of the IPFS Core API, and which are auxiliary functions that aren't specific to the core.

## Proposed Change

One such API call from js-ipfs-api that doesn't fit well into Core is the ability to add a file or directory using [add](https://github.com/ipfs/js-ipfs-api/blob/master/src/request-api.js#L78). Core needs to be as agnostic as possible, and shouldn't be responsible for interacting with the underlying file system at all (think browser support).

This is useful functionality to have though, so I suggest moving the file/directory adding logic into a separate method on the API, like `addFiles`, which can perform the filesystem operations within this module, and translate them to an array of streams and paths to be handed over to the Core API.

## Steps

- [x] remove file/directory adding from `add`
- [x] introduce a new api call that does adding files from the local filesystem (`addFiles`)
- [x] remove url adding from `add`
- [x] introduce a new api call that does adding files from a URL (`addURL`)
- [x] use interface-ipfs-core for testing `add`
- [x] bump a major semver to make it clear that this is a breaking change

---

ping @diasdavid @nginnever @dignifiedquire

**Comment by diasdavid** [comment]
This is all done now 🎉 It was merged with the "next-generation" PR :)
