### ISSUE TITLE
IPFS files cp

### ISSUE THREAD

**Issue by 18dew** [ipfs/js-ipfs-api#283]
Hi All 

Is Ipfs .files.cp in place, if yes then how do we use it.

**Comment by nginnever** [comment]
Hey! 

Yes ipfs.files.cp is in place as seen in the api here https://github.com/ipfs/js-ipfs-api/blob/master/src/api/files.js#L7.

The tests show an example of how to use it here https://github.com/ipfs/js-ipfs-api/blob/master/test/api/files.spec.js#L25-L31

Hope this helps :)

**Comment by 18dew** [comment]
Ya i tried these method but some how its not going thru getting following errors 

ipfs.files.cp("/ipfs/Qm..foo",'tmp')
Promise {
  <rejected> [TypeError: Cannot assign to read only property 'arg' of tmp] }

**Comment by Sija** [comment]
@18dew test code linked here by @nginnever states that you should pass `array` as first argument - like `ipfs.files.cp(['/original', '/copy'])`

**Comment by diasdavid** [comment]
@Sija thank you for clarifying how to use the files.cp API. @18dew have you hit any other issue? Closing this one, reopen if necessary :)
