### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by zbyte64** [ipfs/js-ipfs-api#295]
Currently we only have one example that does an `ls`. I would really like to see examples where:
- a name is resolved and the contents are fetched
- cat is used to display the IPFS readme
- anything to do with ipfs.object
- publish some data

**Comment by diasdavid** [comment]
@zbyte64 did looking of the tests provide any help? They provide examples for each command as each test is design for each of the API calls.

I agree that having more examples on the front page would be great. Would you like to help us get it? :)

**Comment by diasdavid** [comment]
Hey @zbyte64, we've new examples that fulfil your request + help with the bundling of js-ipfs-api, check them out here: https://github.com/ipfs/js-ipfs-api/tree/master/examples

Hope it helps, closing this issue, let us know if you run into any other trouble :)
