### ISSUE TITLE
Different hashes in js-ipfs-api compared to go-ipfs

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/js-ipfs-api#300]
I have this example project set up: https://github.com/VictorBjelkholm/ipfs-inconsistency

It contains a index.js that adds the `test-data` directory to ipfs.

If you run that file with `node index.js`, you get a list of different hashes compared to if you add the files with `go-ipfs` (by running `ipfs add -r test-data`) which is weird.

Example output from `js-ipfs-api`:
```
added QmPsoRskVhY7GowC75kBBncVHBkTyHAktiNxSmyhNgKxn3 test-data/readme.md
added QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH test-data/src
added Qmdn9zEotP3h7p7roppE3PzwtdiAwYPr6mQettwij1JJN4 test-data/src/lib.js
```
Output from ID (only versions):
```
{
  AgentVersion: 'go-ipfs/0.3.11',
  ProtocolVersion: 'ipfs/0.1.0' }
```

Example output from `go-ipfs`
```
added QmPsoRskVhY7GowC75kBBncVHBkTyHAktiNxSmyhNgKxn3 test-data/readme.md
added Qmdn9zEotP3h7p7roppE3PzwtdiAwYPr6mQettwij1JJN4 test-data/src/lib.js
added QmSZwVMTt2stxqs3MiAUCk9w6wX3n5Z8tiJoQUv4DDbmeT test-data/src
added QmSPvto83drjXTSLGUhYVzu1n1eKAu8o6Jd8JWrDQCCu2c test-data
```
Output from ID (only versions):
```
{
	"AgentVersion": "go-ipfs/0.3.11",
	"ProtocolVersion": "ipfs/0.1.0"
}
```

There are two problems with the output from `js-ipfs-api`. 1) The folder itself is not included 2) the hashes are not the same...

What could be wrong here?

**Comment by diasdavid** [comment]
This is very strange indeed. The first thing I noticed is that you are using go-ipfs 0.3.11, while you are using js-ipfs-api latest. go-ipfs 0.4.x introduced some breaking changes on the http-api and we do not recommend using latest js-ipfs-api with it (we do really recommend upgrading to the latest version of go-ipfs, currently 0.4.2)

Then, the second bug is that js-ipfs-api `addFiles` call is not sending the enclosing folder that is being added. _This is a known bug_. In fact, I believe we talked about this the other day, right? 

The third bug, which is different hashes, seems like a new bug, it feels like js-ipfs-api is sending the file that lives in a subdir too late.

Thank you for detecting this! Could you convert it to a failing test? I'll try to look into it asap, but also, if you have time to go through the code, it will be much appreciated :)

**Comment by VictorBjelkholm** [comment]
@diasdavid I'll try to update and report back.

Secondly, yes, I have a PR opened about that ( https://github.com/ipfs/js-ipfs-api/issues/297 ) but was unsure since the hashes was different.

I'll see if I can take a look at a later point. 

Thanks!

**Comment by VictorBjelkholm** [comment]
@diasdavid Yes, updating to ipfs 0.4.2 did indeed solve the issue.

New output:
```
➜  ipfs-inconsistency git:(master) node index.js
Added QmPsoRskVhY7GowC75kBBncVHBkTyHAktiNxSmyhNgKxn3 test-data/readme.md
Added Qmdn9zEotP3h7p7roppE3PzwtdiAwYPr6mQettwij1JJN4 test-data/src/lib.js
Added QmSZwVMTt2stxqs3MiAUCk9w6wX3n5Z8tiJoQUv4DDbmeT test-data/src
Added QmSPvto83drjXTSLGUhYVzu1n1eKAu8o6Jd8JWrDQCCu2c test-data
➜  ipfs-inconsistency git:(master) ipfs add -r test-data/
added QmPsoRskVhY7GowC75kBBncVHBkTyHAktiNxSmyhNgKxn3 test-data/readme.md
added Qmdn9zEotP3h7p7roppE3PzwtdiAwYPr6mQettwij1JJN4 test-data/src/lib.js
added QmSZwVMTt2stxqs3MiAUCk9w6wX3n5Z8tiJoQUv4DDbmeT test-data/src
added QmSPvto83drjXTSLGUhYVzu1n1eKAu8o6Jd8JWrDQCCu2c test-data
```

Thanks for that! Maybe it'll be useful to add a warning of some sorts if you're running `js-ipfs-api` with an incompatible version of `go-ipfs`?
