### ISSUE TITLE
files.add: Argument 'key' is required

### ISSUE THREAD

**Issue by chpio** [ipfs/js-ipfs-api#302]
*ipfs.files.add* throws an `Argument 'key' is required` exception

im calling it with an array:
```js
const files = [
 {
  path: 'dir/file.txt',
  content: aFileStream,
 },
 // and so one
]

await ipfs.files.add(files, {recursive: true});
```

version: 6.0.1

**Comment by chpio** [comment]
my fault! i assumed the docker image *ipfs/go-ipfs:latest* is the latest *working* (not dev) build

**Comment by diasdavid** [comment]
@chpio good catch, we have to update that.

@lgierth, @whyrusleeping, seems that our Docker image is out of date, can you publish a new one?
