### ISSUE TITLE
Create example: uploading binary file via browser form "file upload"

### ISSUE THREAD

**Issue by harlantwood** [ipfs/js-ipfs-api#316]
Below are notes from my post to [a thread on ipfs-users](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ipfs-users/OoTiXEIvVNQ/byaOGVRpBwAJ):

I wrestled with this one for a while, trying to upload images to IPFS from the browser.  It's a bit tricky.  

Here is a gist of a simplified version of the working solution that I ended up with:

https://gist.github.com/harlantwood/58990ebe47b54e05020a13a45a124dff

This example is in ES6 / React, but all the important stuff should work in other contexts.

Important note:  **I had to require buffer directly** -- using IpfsApi.Buffer did not work for me, maybe because of a version difference, not sure.  And yes you need the trailing slash: 

`Buffer = require('buffer/').Buffer`

Otherwise you will get the nodejs built in buffer.

**Comment by harlantwood** [comment]
Could be combined with #315, or could be a separate example.

**Comment by diasdavid** [comment]
Hey @harlantwood o/ Would you like to PR the working example for this repo? It would be greatly appreciated :)

**Comment by harlantwood** [comment]
Sure, ping me again if you see that I haven't done it within a few weeks or
so.

**Comment by lidel** [comment]
@harlantwood any luck? I tried to use upstream browser bundle but it I am stuck due to missing `Buffer`:  https://github.com/ipfs/js-ipfs-api/issues/528

**Comment by harlantwood** [comment]
Added example in #539.

**Comment by diasdavid** [comment]
Thank you @harlantwood :)
