### ISSUE TITLE
swarm.peers() doesn't return a Promise

### ISSUE THREAD

**Issue by haadcode** [ipfs/js-ipfs-api#317]
At some point the swarm commands were re-implemented and in the process, their return type was changed from Promise to callback. This breaks the use of js-ipfs-api in older projects.

Furthermore, the APIs return different data: on js-ipfs-api, it's `{ Strings: [<addresses>] }` and on js-ipfs it's an array of Multiaddresses.

**Comment by diasdavid** [comment]
It now returns a promise (see: https://github.com/ipfs/js-ipfs-api/blob/master/src/api/swarm.js#L8)

And we are making the API compatible through interface-ipfs-core, we just need to get the pull-streams in and change the libp2p to support multiaddrs without ipfs ids too. Follow here:

https://github.com/ipfs/js-ipfs/issues/439 :)
