### ISSUE TITLE
Assumptions about init-docs hashes

### ISSUE THREAD

**Issue by lgierth** [ipfs/js-ipfs-api#365]
I can't quite pin down what the issue is, but I think it's something about the assumptions js-ipfs-api makes about the init-docs hashes. My observations:

- I updated the init-docs in go-ipfs, and the js-ipfs build is failing. [1] It looks like only the `.refs` tests fail, while other tests seem to add the init-docs themselves and use the hash resulting from that.
- The whole `npm test` run works fine locally. Does js-ipfs-api use the go-ipfs from `$PATH`? Does it generate ephemeral fs-repos? I do have the new init-docs in my `~/.ipfs` fs-repo, and the tests might use that fs-repo in one spot and succeed because of that?

I don't have a good idea but it's blocking ipfs/go-ipfs#2997 which is a trivial PR in itself but turned into a yak shaving.

[1] http://ci.ipfs.team:8111/viewLog.html?buildId=5376&buildTypeId=GoIpfs_JsIpfsApiTests&tab=buildLog#_focus=1948

**Comment by diasdavid** [comment]
@lgierth yeah, some or the 'old' tests use the assumption that the repo is already populated with something.

**Comment by whyrusleeping** [comment]
@diasdavid @dignifiedquire any update here?

**Comment by dignifiedquire** [comment]
@whyrusleeping I will take a look at this today

**Comment by VictorBjelkholm** [comment]
Kind of related, maybe we should have a separate repository with test data we can use across the organization, with some json structure + files that we can use a central point for the data?
