### ISSUE TITLE
Cannot include ipfs-api and ipfs-merkle-dag in the same page

### ISSUE THREAD

**Issue by nycoliver** [ipfs/js-ipfs-api#366]
Unable to use both scripts in the same page. I assume this also affects other js-ipfs-\* modules.

``` html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Test</title>
    <script src="https://npmcdn.com/ipfs-api/dist/index.min.js"></script>
    <script src="https://npmcdn.com/ipfs-merkle-dag/dist/index.min.js"></script>
  </head>
</html>
```

throws `Error: only one instance of babel-polyfill is allowed`

**Comment by dignifiedquire** [comment]
Yes that is a current issue, we are working to resolve it here: https://github.com/dignifiedquire/aegir/issues/36 and https://github.com/ipfs/js-ipfs/issues/431 

The gist of it, is that we have a version without babel-polyfill but that creates other problems currently, which we are still looking into fixing before we can do a release without it.

**Comment by lidel** [comment]
I have similar problem with `is-ipfs` and `js-ipfs-api` (https://github.com/lidel/ipfs-firefox-addon/issues/152)
Is there any workaround other than manually building custom artifact that includes both libraries?

**Comment by aakilfernandes** [comment]
+1. having this problem trying to include both `js-ipfs-api` and `multihashing`

**Comment by dignifiedquire** [comment]
This will be fixed once #390 is merged and released

**Comment by dignifiedquire** [comment]
No more transpilation in the latest releases. So you can go a head and use them together :) Please not that ipfs-merkle-dag was deprecated in favor of https://github.com/ipld/js-ipld-dag-pb/

**Comment by diasdavid** [comment]
🎉

**Comment by lidel** [comment]
Thanks, works fine now! :rocket:
