### ISSUE TITLE
Migrate to pull-streams

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs-api#367]
Ref https://github.com/ipfs/js-ipfs/issues/403
- Expose both pull and node-stream interface
- Use pull-streams for all internals

**Comment by diasdavid** [comment]
This has to go through a interface-ipfs-core proposal first

**Comment by dignifiedquire** [comment]
> This has to go through a interface-ipfs-core proposal first

Only the external api changes, not the internal refactor.

**Comment by diasdavid** [comment]
external refactor? the http libraries are regular Streams base, adding pull-streams to internals would mean a double wrap

**Comment by dignifiedquire** [comment]
> http libraries are regular Streams base

Yes, but it's not clear if we should continue using them.

**Comment by diasdavid** [comment]
@dignifiedquire I'm not sure if I understand what you have in mind, since adding pull-streams to internals would mean that we need to wrap the http request in a pull-streams based, is that what you propose? If so, my question is: Do we really need to do that? What is the need?

**Comment by dignifiedquire** [comment]
Given the current libraries we use this probably doesn't make sense, unless we expose pull-streams on the interface level. Going to close this for now.
