### ISSUE TITLE
Exposing API with hidding of underlying network

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/js-ipfs-api#387]
In ipfs-firefox-addon we would like to expose the js-ipfs-api, but we don't want to expose infrastructure information like addresses.

Ref https://github.com/lidel/ipfs-firefox-addon/issues/37

**Comment by diasdavid** [comment]
@Kubuxu why not wrap the ipfs object with something that exposes only the methods that you want the users to have access to, would that fit your need?

**Comment by diasdavid** [comment]
Never got back here. Closing. Let me know if this is still important and/or the solution provided is not enough.
