### ISSUE TITLE
Bundling - js-ipfs-api does not work in browsers

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/js-ipfs-api#389]
js-ipfs-api fails on loading currently in browsers, error is `dag-node.js:16 - Uncaught TypeError: fs.readFileSync is not a function` which I tracked down coming from `js-ipfs-merkle-dag` (here to be exact: https://github.com/ipfs/js-ipfs-merkle-dag/blob/893aff1940a9281e31259affed05d983ca738478/src/dag-node.js#L12)

Issue in the js-ipfs-merkle-dag repository: https://github.com/ipfs/js-ipfs-merkle-dag/issues/48

**Comment by dignifiedquire** [comment]
Which version are you using? How did you build the bundle?

**Comment by VictorBjelkholm** [comment]
9.0.0 of js-ipfs-api, which loads ipfs-merkle-dag@0.7.3. Building with webpack, important parts from config:

```
module.exports = {
  node: {
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  }
}
```

Those things comes from my usage of js-ipfs-api before

**Comment by VictorBjelkholm** [comment]
@dignifiedquire you can see full code here: https://github.com/VictorBjelkholm/webpack-node-ipfs-api-demo

**Comment by dignifiedquire** [comment]
@VictorBjelkholm you are missing brfs like this: https://github.com/dignifiedquire/aegir/blob/master/config/webpack.js#L104

There is a reason we use a shared webpack config to build all our things.

**Comment by VictorBjelkholm** [comment]
@dignifiedquire we can't possibly be asking all users of `js-ipfs-api` to use our shared webpack config though, no? I'm expecting this module to work no matter how I include it, with webpack, browserify or whatelse, without using our configuration (but yeah, it's hard work)

**Comment by diasdavid** [comment]
`brfs` has been available for a long time, it should be a stranger anymore. However, I do agree that these things need proper documentation. 

Both `js-ipfs-api` and `js-ipfs` require for things to be transpiled/replaced in the browserifying process. This has to be documented.

**Comment by VictorBjelkholm** [comment]
@diasdavid correct me if I'm wrong but we're publishing the built-files to be able to avoid this? In my mind, people should be able to use our libraries without any configuration on their side

**Comment by diasdavid** [comment]
`dist version` -> bundled version === no worries

`require version` -> the version that we also use, might require handling with nuances like shimming node-forge, fs, libp2p-ipfs into libp2p-ipfs-browser and so on. 

Of course that in a perfect world, a require would be all you need to roll any module in the browser, unfortunately, we known that to get Universal JS, there are some things that need to be handled. It is true that we can work towards making our modules the more hassle free possible, but since if that is not possible throughout the entire codebase, the best is just to be consistent and have a clear section in the Readme that explains how to handle situations where modules have to be shimmed.

**Comment by freeaccount255** [comment]
My code:
`uploadFile(){
			var files=document.getElementById('files').files;
			for(var i=0;i<files.length;i++){
				var file=files[i];
				if(!file) return;
				var reader=new FileReader();
				reader.addEventListener("load", function (event) {
					var data = event.target.result;
					data = new window.ipfs.Buffer(data.substr(data.indexOf(',') + 1), 'base64');
					addFileToIPFS(file.name,data);
				});
				
				reader.readAsDataURL(file);
			}
		}`
`function addFileToIPFS(path , content){
	var files = [{
		path: path,
		content: content
	}];
	
	ipfs.add(files,function(err, res) {
		if(err || !res) return;
		console.log(res);
	});
}`

**Comment by karlfloersch** [comment]
I'm trying to get `js-ipfs-api` working with webpack as well. I've gotten past a lot of the `fs. readFileSync` errors with this bit of configuration:
```
    preLoaders: [
      {
        test: /\.js$/,
        loader: 'transform?brfs',
        include: /node_modules\/(ipfs-merkle-dag|libp2p-crypto)/,
      },
    ]
```

I've now run up against a new issue with the `forge.js` package. I'm getting the following error:
```
  Uncaught ReferenceError: Invalid left-hand side in assignment
  at /.../internals/testing/test-bundler.js:111983 <- webpack:///~/node-forge/js/forge.js:50:0
```
This may be related to this: https://github.com/digitalbazaar/forge/issues/198

I'll follow up with any updates, and would love any suggestions on potential ways to proceed

**Comment by nycoliver** [comment]
I had these issues as well. As a workaround, I'm using the script tag
```
<script src="https://npmcdn.com/ipfs-api/dist/index.js"></script>
```

**Comment by alanshaw** [comment]
Just wondering how to use this with browserify?

Is the recommendation to `require('ipfs-api/dist')`? If so, I'm currently seeing the following issue:

```sh
Error: Cannot find module 'js/forge' from 'node_modules/ipfs-api/dist'
```

**Comment by alanshaw** [comment]
Note to anyone who's reading this, 'ipfs-api/dist' is a bundled version, but it is not UMD so you can't `require` it with browserify.

**Comment by diasdavid** [comment]
This should not be an issue anymore, Async Crypto PR has been merge 🎉🎉🎉🎉

**Comment by VictorBjelkholm** [comment]
Cool! It is indeed working now, amazing job @dignifiedquire! Now https://github.com/VictorBjelkholm/webpack-node-ipfs-api-demo builds and runs correctly!

**Comment by diasdavid** [comment]
@VictorBjelkholm could you bring that demo to this repo, to the examples folder please?

**Comment by VictorBjelkholm** [comment]
@diasdavid hmmm, let me think about that.

Ok, I'll do it!

**Comment by vurumadla** [comment]
i am facing this issue during building through dev.js. can anyone sugegst the solution.



WARNING in ./~/ipfs-js/~/ipfs-api/dist/ipfsapi.min.js
Critical dependencies:
1:461-468 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/ipfs-js/~/ipfs-api/dist/ipfsapi.min.js 1:461-468

ERROR in ./~/ipfs-api/lib/get-files-stream.js
Module not found: Error: Cannot resolve module 'fs' in /home/centos/PrivateSecurities1/node_modules/ipfs-api/lib
 @ ./~/ipfs-api/lib/get-files-stream.js 33:11-24

ERROR in ./~/glob/glob.js
Module not found: Error: Cannot resolve module 'fs' in /home/centos/PrivateSecurities1/node_modules/glob
 @ ./~/glob/glob.js 43:9-22

ERROR in ./~/glob/sync.js
Module not found: Error: Cannot resolve module 'fs' in /home/centos/PrivateSecurities1/node_modules/glob
 @ ./~/glob/sync.js 4:9-22

ERROR in ./~/ipfs-merkle-dag/lib/dag-node.js
Module not found: Error: Cannot resolve module 'fs' in /home/centos/PrivateSecurities1/node_modules/ipfs-merkle-dag/lib
 @ ./~/ipfs-merkle-dag/lib/dag-node.js 9:9-22

ERROR in ./~/fs.realpath/index.js
Module not found: Error: Cannot resolve module 'fs' in /home/centos/PrivateSecurities1/node_modules/fs.realpath
 @ ./~/fs.realpath/index.js 8:9-22

**Comment by VictorBjelkholm** [comment]
@vurumadla I edited your comment to add code tags, making errors easier to read.

Did you try the example over at https://github.com/ipfs/js-ipfs-api/blob/master/examples/bundle-webpack? Specifically, if you use https://github.com/ipfs/js-ipfs-api/blob/12802eb9d1db63c6a3ba57ee906005015daf5a76/examples/bundle-webpack/webpack.config.js#L28-L32 in your webpack config, it should fix your issue

**Comment by bohendo** [comment]
For those googling the same error I was:
```
ERROR in ./node_modules/fs-constants/browser.js
Module not found: Error: Can't resolve 'constants' in '/app/node_modules/fs-constants'
 @ ./node_modules/fs-constants/browser.js 1:17-37
 @ ./node_modules/tar-stream/pack.js
 @ ./node_modules/tar-stream/index.js
 @ ./node_modules/ipfs-api/src/utils/tar-stream-to-objects.js
 @ ./node_modules/ipfs-api/src/files/get.js
 @ ./node_modules/ipfs-api/src/utils/load-commands.js
 @ ./node_modules/ipfs-api/src/index.js
 @ ./src/actions/arcActions.ts
 @ ./src/layouts/AppContainer.tsx
 @ ./src/App.tsx
 @ ./src/index.tsx
 @ multi react-hot-loader/patch webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server ./src/index.tsx
```

Which could be quieted by adding `externals: { constants: 'constants' }` to webpack config but then the browser would complain that it couldn't find `constants`.

Replacing `require('ipfs-api')` with `require('ipfs-api/dist')` fixed both of these issues & now everything' working smoothly
