### ISSUE TITLE
files.flush is missing

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs-api#411]
Need this in npm-on-ipfs

**Comment by diasdavid** [comment]
Oh, that is a new command. One way to force flush meanwhile is to do a `ipfs files stat /`

**Comment by dignifiedquire** [comment]
> Oh, that is a new command. One way to force flush meanwhile is to do a ipfs files stat /

Jup doing that currently, but we should still have it :)

**Comment by diasdavid** [comment]
Thanks @hacdias for shipping this :)

**Comment by hacdias** [comment]
It was my pleasure :)
