### ISSUE TITLE
Using js-ipfs-api with Webpack and browserify

### ISSUE THREAD

**Issue by chriswingler** [ipfs/js-ipfs-api#412]
Hi, I'm trying to bundle this with webpack, and I'm wondering what the correct code would be?

`import IpfsAPI from 'ipfs-api';` doesn't work.

**Comment by dignifiedquire** [comment]
We just released a new version which makes it much more compatible with `webpack` but you still need some tweaks to makes sure it loads the right things. You can see the details here: 
- `alias`rules https://github.com/dignifiedquire/aegir/blob/master/config/webpack.js#L28-L38
- enable node `Buffer`: https://github.com/dignifiedquire/aegir/blob/master/config/webpack.js#L52-L54

**Comment by diasdavid** [comment]
@dignifiedquire could you provide an help text for our README with these notes? In the same way that: https://github.com/ipfs/js-ipfs-api#in-the-browser-through-browserify

**Comment by diasdavid** [comment]
Hi @chriswingler! We've shipped last week two awesome examples, one with browserify bundling and another one with WebPack, it should answer all your questions.

Closing this issue, feel free to reach out again if there is still some hurdles.

**Comment by chriswingler** [comment]
Hi again @diasdavid.  I'm getting this error during `npm install` in the webpack example with node v7.

`> webcrypto-core@0.1.2 install /home/chris/workspace/js-ipfs-api/examples/bundle-webpack/node_modules/node-webcrypto-ossl/node_modules/webcrypto-core
> npm run build:es5


> webcrypto-core@0.1.2 build:es5 /home/chris/workspace/js-ipfs-api/examples/bundle-webpack/node_modules/node-webcrypto-ossl/node_modules/webcrypto-core
> tsc --module commonjs --target es5

sh: 1: tsc: not found

npm ERR! Linux 4.8.0-27-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:es5"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! webcrypto-core@0.1.2 build:es5: `tsc --module commonjs --target es5`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the webcrypto-core@0.1.2 build:es5 script 'tsc --module commonjs --target es5'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webcrypto-core package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc --module commonjs --target es5
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webcrypto-core
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webcrypto-core
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /home/chris/workspace/js-ipfs-api/examples/bundle-webpack/node_modules/node-webcrypto-ossl/node_modules/webcrypto-core/npm-debug.log
npm WARN bundle-browserify@1.0.0 No repository field.
npm ERR! Linux 4.8.0-27-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! webcrypto-core@0.1.2 install: `npm run build:es5`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webcrypto-core@0.1.2 install script 'npm run build:es5'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webcrypto-core package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:es5
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webcrypto-core
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webcrypto-core
npm ERR! There is likely additional logging output above.
`

**Comment by VictorBjelkholm** [comment]
hey @chriswingler, seems you're using an old version of js-ipfs-api. Could you try pulling latest master and reinstalling node_modules?

We had an open issue about this here: https://github.com/ipfs/js-ipfs-api/issues/424

**Comment by chriswingler** [comment]
Hey @VictorBjelkholm I just did a fresh clone of master and I'm getting this error.  Should I be pulling from a different branch?

**Comment by VictorBjelkholm** [comment]
@chriswingler no, master should work. I just tried it myself. Can you verify you're on commit 723b4b01fc910d7c8d5acbfdf224df0d6c5064a6 ?

**Comment by chriswingler** [comment]
Yes, I'm on that commit.  However, it looks like I was having a problem with permissions.  Must have accidentally cloned as root.

I have a new problem though, got the example running but it's not showing any ID, peer, etc information.

**Comment by chriswingler** [comment]
Oh, sorry I think I need to setup CORS.  Thanks @VictorBjelkholm.
