### ISSUE TITLE
New go-ipfs feature: ipfs swarm list connections

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs-api#413]
We need to upgrade the swarm API implementation to follow: https://github.com/ipfs/go-ipfs/pull/3352

**Comment by Kubuxu** [comment]
It should be possible to support both the old and new api by detecting the type of call result.

**Comment by whyrusleeping** [comment]
@Kubuxu Yeah, thats what i'm doing on the go side right now, basically just checking whats in the json map that gets returned

**Comment by diasdavid** [comment]
done in https://github.com/ipfs/js-ipfs-api/pull/427
