### ISSUE TITLE
Add possibility to get all peers of a pubsub topic to js-ipfs-api

### ISSUE THREAD

**Issue by haadcode** [ipfs/js-ipfs-api#423]
We have a way to get a list of peers that we're pubsubbing to but it's not exposed in js-ipfs-api currently.

This would be hugely beneficial for Orbit, and others too, so let's add that.

https://github.com/ipfs/go-ipfs/blob/master/core/commands/pubsub.go#L267

**Comment by VictorBjelkholm** [comment]
Ref for pending PR adding pubsub (but not this command, would be after): https://github.com/ipfs/js-ipfs-api/pull/377

**Comment by diasdavid** [comment]
If I understand correctly, it is done here: https://github.com/ipfs/js-ipfs-api/pull/471
