### ISSUE TITLE
Create examples of how to use js-ipfs-api with browserify and WebPack 

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs-api#428]
ref: https://github.com/ipfs/js-ipfs/issues/429#issuecomment-260361076

**Comment by dignifiedquire** [comment]
Browserify: https://github.com/ipfs/js-ipfs-api/tree/master/examples/browser-add
Webpack: https://github.com/ipfs/js-ipfs-api/pull/421

**Comment by diasdavid** [comment]
Ok, I think I'll rename the browserify one to make it more obvious that is the perfect example for that, sounds good?

**Comment by diasdavid** [comment]
we have examples now wooot! https://github.com/ipfs/js-ipfs-api/tree/master/examples
