### ISSUE TITLE
11.1.0 breaks error in callback

### ISSUE THREAD

**Issue by nycoliver** [ipfs/js-ipfs-api#438]
Making requests when the daemon is not running throws an XHR error, as expected. However in the 11.1.0 the callback is never called. For example:

```html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://unpkg.com/ipfs-api@11.1.0/dist/index.js"></script>
    <script>
      var ipfs = window.IpfsApi();
      ipfs.id(function(err, res) {
        if (err) {
          console.log(err)
        }
      })
    </script>
    <title>IPFS Test</title>
  </head>
  <body>
  </body>
</html>

```

<img width="643" alt="screen shot 2016-11-22 at 3 16 42 pm" src="https://cloud.githubusercontent.com/assets/2553061/20540290/b372aa7a-b0c6-11e6-9539-d947b5f5db12.png">

vs 11.0.1:

<img width="640" alt="screen shot 2016-11-22 at 3 17 35 pm" src="https://cloud.githubusercontent.com/assets/2553061/20540316/d077e202-b0c6-11e6-83e3-9dc97e84667b.png">

**Comment by diasdavid** [comment]
@nycoliver this was the same problem that @pfrazee was experiencing, fixed now: https://github.com/ipfs/js-ipfs-api/pull/445 :)
