### ISSUE TITLE
aegir is still wonky on release

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs-api#442]
I've experienced two problems:

- when build happens, it runs out of memory and throws (because it has to build twice, for browser tests and for release, if we take out of the browser build, it works)
- when doing the bump 11.1.0 on a release-minor becomes 111.2.0. Fortunately this time I was paying a lot of attention and stopped it before pushing to github and releasing to npm

@dignifiedquire I believe the first is because the dedup plugin stopped working and so it is taking more memory now. The second error is that gulp-bump thing, but I though it was fixed, thoughts?

**Comment by dignifiedquire** [comment]
- I haven't seen any oom issues with webpack what so ever anymore, maybe sth changed recently.
- The dedupe plugin has been dropped here: https://github.com/webpack/webpack/pull/3266 but it seems there is an alternative we can try: https://github.com/webpack/webpack/pull/3266#issuecomment-260623603 so this might be the issue you are having
- When does the actual error happen? This should be independent of the two builds as they are separated and shouldn't influence each other.
- There is an issue open here for the version bump here: https://github.com/stevelacy/gulp-bump/issues/62

**Comment by diasdavid** [comment]
> When does the actual error happen? This should be independent of the two builds as they are separated and shouldn't influence each other.

@dignifiedquire try to run npm release-minor, it will fail on the build task, but if you disable browser tests (first build), it goes through

**Comment by diasdavid** [comment]
aegir is good again :D
