### ISSUE TITLE
Trouble adding folders with specific kinds of characters in the folder

### ISSUE THREAD

**Issue by elsehow** [ipfs/js-ipfs-api#450]
Adding folders with `{recursive: true}` works on all of the folders I try, even big ones.

However, when adding a folder with characters like "[" or "(" in the name, it fails in a mysterious way:

```
> var ipfs = ipfsAPI('localhost', '5001', {protocol: 'http'}) 
undefined
> function cb (err, res) { console.log(err, res) }
undefined
> var path = '/Users/ffff/Music/John Coltrane - A Love Supreme (Vinyl) (1964) [V0]/'
undefined
> ipfs.util.addFromFs(path, {recursive: true}, cb)
null []
```
When I add this folder with `ipfs add -r`, it works with no problem.

**Comment by nycoliver** [comment]
Relevant: https://github.com/ipfs/js-ipfs-api/issues/114

**Comment by elsehow** [comment]
Thanks for the pointer @nycoliver.

I wrote a test that fails `tests/ipfs-api/util.spec.js`:

```javascript
  it('.fsAdd a directory with an odd name', (done) => {
    const filesPath = path.join(__dirname, '../fixtures/weird name folder [v0]')
    ipfs.util.addFromFs(filesPath, { recursive: true }, (err, result) => {
      expect(err).to.not.exist
      expect(result.length).to.be.above(8)
      done()
    })
  })
```

Will do a bit more digging when I get a chance

**Comment by elsehow** [comment]
This issue happens becuase filenames are passed into a glob [see L47 in `get-files-stream.js`](https://github.com/ipfs/js-ipfs-api/blob/master/src/get-files-stream.js#L47). This issue is resolved when we escape the characters that have special, glob-y significance. PR coming soon!

**Comment by diasdavid** [comment]
12.0.1 released with fix by @elsehow. Thank you @elsehow :D
