### ISSUE TITLE
object.data gives .data undefined

### ISSUE THREAD

**Issue by pfrazee** [ipfs/js-ipfs-api#453]
Every so often, I get output from `object.data()` which, when unmarshaled, looks like this:

```
Data {
  type: 'file',
  data: undefined,
  blockSizes: [ 7864320, 7864320, 6346088 ],
  addBlockSize: [Function],
  removeBlockSize: [Function],
  fileSize: [Function],
  marshal: [Function] }
```

This webm, for instance, in the example video player: fs:/ipfs/QmTKZgRNwDNZwHtJSjCp6r5FYefzpULfy37JvMt9DwvXse/video.webm

Any idea why this is happening? Is it possible that certain files (maybe because of size) need to have their data accessed via a different method?

**Comment by diasdavid** [comment]
> files (maybe because of size) need to have their data accessed via a different method?

That is what is happening, the `object` API is just for DAG nodes, a DAG node has a cap of 256KiB, so, when you add a file to IPFS, what you are doing is chunking the file and putting each chunk into a separate DAG node and create a node that points to all the chunks. We call that `unixfs`.

To fetch a file like that webm video, you need to use the Files API -- https://github.com/ipfs/interface-ipfs-core/tree/master/API/files --. To learn more about unixfs, check:

- https://github.com/ipfs/js-ipfs-unixfs
- https://github.com/ipfs/js-ipfs-unixfs-engine

**Comment by pfrazee** [comment]
Ok got it, thanks!
