### ISSUE TITLE
Errors during tests are not displayed

### ISSUE THREAD

**Issue by haadcode** [ipfs/js-ipfs-api#468]
When errors happen during tests, they're not displayed in the console output but only get an generic npm error log:

```
> gulp test:node

[16:40:59] Using gulpfile ~/code/js-ipfs/gulpfile.js
[16:40:59] Starting 'test:node'...
[16:40:59] Starting 'libnode:start'...
Starting at /tmp/ipfs-test-934351
Starting at /tmp/ipfs-test-048139
Starting at /tmp/ipfs-test-805248
Starting at /tmp/ipfs-test-028835
Swarm listening on /ip4/127.0.0.1/tcp/20012/ws
Swarm listening on /ip4/127.0.0.1/tcp/10012

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test:node"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! ipfs@0.18.0 test:node: `gulp test:node`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ipfs@0.18.0 test:node script 'gulp test:node'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ipfs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp test:node
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ipfs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ipfs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/haad/code/js-ipfs/npm-debug.log
```

Expected behaviour is to display the correct error and its stack trace.

@dignifiedquire, I suspect this is something to do with aegir?

**Comment by VictorBjelkholm** [comment]
Seeing the same thing with the lint command, maybe this is related? https://github.com/dignifiedquire/aegir/issues/67

**Comment by diasdavid** [comment]
@haadcode is that coming from js-ipfs-api master for you? I only have seen that happen when it OOM

**Comment by VictorBjelkholm** [comment]
@diasdavid not sure it's OOM since the exit status is 1. If it's OOM, it should be killed with SIGKILL which would be 137. But then maybe the exit status in the logs above is what npm outputs after running the command, rather than the exit code from the daemon/process.

**Comment by dignifiedquire** [comment]
@VictorBjelkholm it is related, something something gulp is swallowing errors :(

**Comment by VictorBjelkholm** [comment]
@dignifiedquire so let's continue in https://github.com/dignifiedquire/aegir/issues/67 which I just changed the title of to include "(and possible others)"

**Comment by diasdavid** [comment]
@VictorBjelkholm sounds good :)
