### ISSUE TITLE
DAGLinks should allow for 0 size links or optional .

### ISSUE THREAD

**Issue by tswindell** [ipfs/js-ipfs-api#497]
Currently there is a js-ipfs-api limitation, where it makes sure that the size of a link is greater than zero. Could we discuss removing this limitation, as size doesn't always make sense in every application. Maybe we could even go a step further and make the size property optional in DAGLink JSON representations when creating them and set them to zero internally.

**Comment by diasdavid** [comment]
Could you illustrate a use case for that? DAGLinks (specific to the dagPB format) have aways a size bigger than 0, since the serialized MerkleDAG protobuf is always bigger than 0, in IPFS there are no hashes to of 0 bytes.

**Comment by tswindell** [comment]
No use case per se, though I use them because I'm lazy when doing my own data structures. But go-ipfs allows 0 size links so ...

**Comment by diasdavid** [comment]
that sounds like a bug in go-ipfs then //cc @Kubuxu @whyrusleeping

**Comment by diasdavid** [comment]
@Kubuxu is this correcT?
