### ISSUE TITLE
ipfs-api webcomponent

### ISSUE THREAD

**Issue by krl** [ipfs/js-ipfs-api#50]
The way i do ipfs-api webcomponent now is like this: 

```html
<script src='ipfsapi.min.js'></script>
<dom-module id="ipfs-api">
  <script>
    (function () {
      Polymer({
        is: 'ipfs-api',
        properties: {
          host: String,
          port: Number
        },
        url: function (path) {
          return 'http://' + this.host + ':' + this.port + path
        },
        ready: function() {
          if (!this.host) {
            var split = window.location.host.split(":")
            this.host = split[0]
            this.port = split[1] || 80
          }
          this.api = ipfsAPI(this.host, this.port)
        }
      });
    })();
  </script>
</dom-module>
```

This is non-ideal since it also exposes a global ipfsAPI, for self-containing reasons it would therefore be nice to have a build step, that browserifies the code + adds the polymer init stuff. We should probably also add the api commands directly to the webmodule object, instead of in .api

The reason i think it makes sense to actually publish the api as a webcomponent, is that you can use it in your browser directly, without any build steps required.

Any thought on this?
@diasdavid @jbenet

**Comment by krl** [comment]
It also contains code to figure out where to access the api at, so that the same code works locally and on the gateway.

**Comment by jbenet** [comment]
> The reason i think it makes sense to actually publish the api as a webcomponent, is that you can use it in your browser directly, without any build steps required.

that sounds good to me. it sounds a bit like how people do hosted CDN-delivered scripts. coupled with IPFS, this is usually fine. one thing of concern is making sure that "if my app X depends on Y, when i build X, i make sure Y is available locally".

thoughts @diasdavid ?

**Comment by diasdavid** [comment]
> The reason i think it makes sense to actually publish the api as a webcomponent, is that you can use it in your browser directly, without any build steps required.

I might be missing some key benefit, but following the goal described, wouldn't we just need:

`<script src="some-URL-that-can-be-also-inside-IPFS.io/ipfsapi.min.js"></script>`

People don't have to build anything, they just have to import it with a <script> tag. This is how every (I'm sure there are some exceptions, but..) JS front end library is done, that is, after the code is finished, someone 'builds it' (as in, minifies, obfuscates, browserifies, coffeefies etc) and make it available at some URL.

WebComponetizing the ipfsapi, adds an extra layer of complexity, devs will not only to import the module, but also polymer in order to use the module

**Comment by jbenet** [comment]
@diasdavid oh, duh! you're totally right. 

wish `<script>` came with `<script src="SRC" as="foo" />`

**Comment by jbenet** [comment]
sigh, the `#include` copy paste hegemony.

**Comment by krl** [comment]
Hmm then i would suggest that we add some logic to figure out if you're in a browser, and default on the window.host, so that we don't have to add this to everything that wants to use the library in webapps.

**Comment by krl** [comment]
#51

**Comment by diasdavid** [comment]
Is this still a goal for ipfsAPI? @krl ?

**Comment by diasdavid** [comment]
Seems it is not a necessary requirement. Closing this one for now.
