### ISSUE TITLE
.swarm test timeout

### ISSUE THREAD

**Issue by JeffDownie** [ipfs/js-ipfs-api#503]
I wasn't sure whether to put this here or in the interface-ipfs-core repository, but occasionally when running the test suite, I get the following error:

> 1) .swarm "before all" hook:
    Error: Timeout of 20000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

This only happens occasionally, but it's quite irritating as I then have to re-run all the tests again if I want to check everything, which takes > 5 minutes on my machine.

**Comment by diasdavid** [comment]
Haven't been able to reproduce it on my machine. @dignifiedquire @VictorBjelkholm have you seen this bug before?

**Comment by diasdavid** [comment]
Closing this one as I never managed to replicate it.
