### ISSUE TITLE
Unsupported type for static module: UnaryExpression

### ISSUE THREAD

**Issue by aakilfernandes** [ipfs/js-ipfs-api#507]
Getting this when bulding the module with webpack (before instantiating).

```
ERROR in ./~/pump/index.js
Module build failed: Error: unsupported type for static module: UnaryExpression
at expression:

  !fs
```

https://gist.github.com/aakilfernandes/4d3c26d41aec0668507498b1600d8020

**Comment by aakilfernandes** [comment]
Node v6.3.0

**Comment by aakilfernandes** [comment]
This can be fixed by locking pump at at 1.0.1. 1.0.2 introduces a bug

**Comment by diasdavid** [comment]
Something should be wrong with your Webpack config. It should pick up on the `fs: null` on the package.json for browser.

**Comment by diasdavid** [comment]
@aakilfernandes do you still have this issue? Never managed to reproduce it. Closing for now, let me know otherwise.
