### ISSUE TITLE
A function that returns the IPFS addresses of files without uploading them

### ISSUE THREAD

**Issue by yxliang01** [ipfs/js-ipfs-api#509]
This would be useful for many applications, especially for experiments.

**Comment by jbenet** [comment]
should be able to be done with `ipfs add --only-hash` (so `ipfs.add({"only-hash": true}, ...)` i think? cc @diasdavid @dignifiedquire

**Comment by diasdavid** [comment]
Exactly, you can do that with the `only-hash` option.

**Comment by yxliang01** [comment]
Thanks. But, when I pass opts with the key `only-hash` to `ipfs.util.addFromFs`, this function never calls the callback.. Help needed.

**Comment by yxliang01** [comment]
By try and error and some analysis, I think has nothing deal with `ipfs.util.addFromFs`. If the file was uploaded before or run with `ipfs add --only-hash` before, `ipfs.util.addFromFs` calls the `cb` almost immediately. But, if the file was brand new to the IPFS, it just hanged without error. I tried to understand the source code, but I haven't really understood it yet...

**Comment by aakilfernandes** [comment]
@yxliang01 you can take a look at this for inspiration

https://github.com/SafeMarket/ux/blob/master/lib/utils/getUnixMultihash.js

I believe the problem is that the multihash depends on the filesystem.

**Comment by yxliang01** [comment]
Thanks @aakilfernandes . While this is handy, I still think `only-hash` should work and do the job perfectly because it can guarantee that no matter how IPFS changes its way calculating the hash, the result is still accurate...

**Comment by yxliang01** [comment]
So... I think this is a bug instead of a question. Anyone has idea?

**Comment by yxliang01** [comment]
Okay, I think I know why. After dipping into the code, I found that add.js doesn't have options support which contradicts the documentation `ipfs.files.add(data, [options], [callback])` at https://github.com/ipfs/interface-ipfs-core/tree/master/API/files#add .

**Comment by santiagorp** [comment]
What happens with this? I saw a branch containing with this which was deleted today.

**Comment by sterlu** [comment]
Any news on this?

**Comment by JonKrone** [comment]
It looks like `files.add` does not support `onlyHash` right now but the unix dagNode creator thing (still trying to figure it all out), [ipfs/js-ipfs-unixfs-engine](https://github.com/ipfs/js-ipfs-unixfs-engine), does so I think we might just need to connect the two.

js-ipfs-unixfs-engine can handle an `onlyHash` option as of https://github.com/ipfs/js-ipfs-unixfs-engine/pull/183.

In a little test, passing a hardcoded `onlyHash` option to the importer [here](https://github.com/ipfs/js-ipfs/blob/master/src/core/components/files.js#L123) and then avoiding the subsequent block call [here](https://github.com/ipfs/js-ipfs/blob/master/src/core/components/files.js#L25) seems to give the hash output but doesn't actually add to the fs.

I'd be happy to work on this. I think the pieces are something like:

* connect the cli options to the fs engine
* tests

**Comment by aiFreak** [comment]
Hello, can you tell me the function to produce only-hash using javascript.

**Comment by vmx** [comment]
@aiFreak A good starting point is the tests: https://github.com/ipfs/js-ipfs-api/blob/3f3ce8a998b42b15623aaed3ed80606cf5ed91cc/test/files.spec.js#L106-L117 You call `ipfs.files.add()` with `{onlyHash: true}` as option.

**Comment by aiFreak** [comment]
@vmx Thanks for your valuable suggestion but i want to generate ipfs hash on webpage without uploading so, that i can compare the hash. so, i want javascript or any client side code for web to generate multihash of ipfs.

**Comment by vmx** [comment]
@aiFreak You can use https://github.com/multiformats/js-multihashing-async to hash the actual data and then https://github.com/multiformats/js-multihash to create a multihash out of it.

**Comment by aiFreak** [comment]
@vmx Actually i have added the data to ipfs using ipfs.add() inside javascript code that gives a ipfs hash. Now, i want to genrate that same hash of the data without running the daemon means outside of ipfs so, for that i need javascrip function or code to generate the ipfs hash through webpage.

**Comment by aiFreak** [comment]
Actually there is a code in node js that gives the same hash but that is in nodejs but i want the code in javascript so that i can use it inside <script> tag.
(https://github.com/ipfs/faq/issues/208)

**Comment by vmx** [comment]
@aiFreak It seems to be supported in js-ipfs (https://github.com/ipfs/js-ipfs/blob/8e3ea44ce260bdd56dd8691e907f55b0eea86c4c/src/core/components/files.js#L26). So you should be able to do something like:

```
const IFPS = require('ipfs')
IPFS.files.add(data, {onlyHash: true}, cb)
```

Please note that I haven't tried that, but I hope you get the general idea.

**Comment by hacdias** [comment]
The `onlyHash` option is supported since https://github.com/ipfs/js-ipfs-api/pull/717 😄

**Comment by JikkuJose** [comment]
If I understand right, there is no direct command in `ipfs` to _just_ get the hash of a file without uploading or doing anything else with it? (Somehow this feels very odd, thats why I am confirming)

**Comment by daviddias** [comment]
@JikkuJose you can use the `--only-hash` option. See https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md#add

**Comment by princesinha19** [comment]
@JikkuJose 
In command line, You can use `-n` with **ipfs add** command to do only hash.

`For eg.. ipfs add -n abc.png`

The command will return ipfs hash without uploading it.

**Comment by JikkuJose** [comment]
@princesinha19 cool then! But wish there was a better named command for it than calling it add itself. I know `-n` is usually used in such context in unix but still feel a more explicit command would have helped.

Also, how did you verify it wasn't added to the repo?

**Comment by princesinha19** [comment]
I added the file first through ` -n` and then checked it on 
http://127.0.0.1:8080/ipfs/IPFS_HASH
Then nothing occurred on screen.

After that, I removed `-n` and then again hit the URL **http://127.0.0.1:8080/ipfs/IPFS_HASH**. Now, I got the image on the browser screen.

**Comment by JikkuJose** [comment]
Aah! I assumed there was a command line way to list the added files :)

**Comment by alanshaw** [comment]
Kindly, please could you move further conversation on this to https://discuss.ipfs.io/ - thank you
