### ISSUE TITLE
Support different mechanisms for caching.

### ISSUE THREAD

**Issue by aakilfernandes** [ipfs/js-ipfs-api#511]
Is there any request caching? If not, would you support a PR that included caching?

**Comment by diasdavid** [comment]
We do `Object API` caching, see: https://github.com/ipfs/js-ipfs-api/blob/master/src/api/object.js#L35

We could do Files Caching as well, just note that caching very large files or directories with a lot of tiny files will quickly destroy the cache, as it will take more time adding and cleaning than actually saving from finding stuff in the cache.

That being said, if a PR with caching that tests for its efficiency in scenarios where big files and/or lots of tiny files are added, then we will be very happy to merge it :)

**Comment by aakilfernandes** [comment]
@diasdavid i was actually thinking of making the PR more like a standardized file-cache provider, that way users could swap in any cache they like

**Comment by aakilfernandes** [comment]
ie something like

`if (options.cacheProvider) { return cacheProvider.get(...) }`

**Comment by diasdavid** [comment]
Sounds that something like that can be quickly achieved with a tiny veneer on top of js-ipfs-api. This way we avoid forcing all of that extra code into everyone's browser application, sounds good?

**Comment by diasdavid** [comment]
Going to close this one for now. It won't be a feature we support as default, you can still take the route I suggested above.
