### ISSUE TITLE
addFromURL fails to follow redirections

### ISSUE THREAD

**Issue by maxlath** [ipfs/js-ipfs-api#513]
```js
ipfs.util.addFromURL('http://covers.openlibrary.org/book/id/969165.jpg')
```
will return the hash of an empty file (`QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH` instead of the expected `QmaL9zy7YUfvWmtD5ZXp42buP7P4xmZJWFkm78p8FJqgjg`) because [`request.js`](https://github.com/ipfs/js-ipfs-api/blob/0295a5a1ad9754f83224d5a236fed94f5c7b202d/src/request.js) doesn't follow redirections

**Comment by maxlath** [comment]
@diasdavid would it be acceptable to introduce a new dependency such as [`follow-redirects`](https://github.com/olalonde/follow-redirects) to solve this issue?

**Comment by diasdavid** [comment]
@maxlath looks promising! My first question was to make sure to check the deps it would bring and the increase in bundle size, but after skimming through follow-redirects, it seems it is the most compact solution we could use :) Move ahead! Thank you.

**Comment by diasdavid** [comment]
Work happening at https://github.com/ipfs/js-ipfs-api/pull/514
