### ISSUE TITLE
instead of uploading a file, it uploads an empty directory

### ISSUE THREAD

**Issue by yxliang01** [ipfs/js-ipfs-api#516]
So, `QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn` is the directory that I am getting when trying to upload a file via `ipfs.files.add`. It will pass the read stream for the file to it.
`{ path: 'C:Temp123.txt',
    hash: 'QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn',
    size: 4
}` is the return from the API. `C:\Temp\123.txt` is the path. If I add with go-ipfs in CLI, it works fine.

Thanks.

**Comment by yxliang01** [comment]
Update: When I pass a `ReadableStream` to `ipfs.files.add`, it has this weird behaviour. But, when I pass

```
{
  path: '/tmp/myfile.txt',
  content: (Buffer or Readable stream)
}
```

It works perfectly. I think this is a bug.

**Comment by diasdavid** [comment]
It is the expected behaviour, see: https://github.com/ipfs/interface-ipfs-core/tree/master/API/files#add

Let us know if you still have a question after reading that

**Comment by yxliang01** [comment]
From wiki, "ipfs.files.add(data, [options], [callback])", Where `data` may be
an array of objects, each of the form
{
  path: '/tmp/myfile.txt',
  content: (Buffer or Readable stream)
}
a `Buffer` instance
a `Readable` stream


Why is that expected to upload an empty directory when I pass a `Readable` stream as `data`?

Thanks.

**Comment by hiteshjoshi1** [comment]
I have the exact same issue, file uploads. I think this issue should remain Open.
But when i try to get to view it using cat and the file hash, it says it is a directory.
http://127.0.0.1:5001/api/v0/cat?arg=QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn

`exports.uploadFile = function(req, res) {

    var files = req.files.files;
    ipfs.files.add(files, function(err, response) {
        if (err) {
            console.log('addition to ipfs failed');
            res.status(500).json({
                "message": "IPFS add failed"
            });
        } else {
            console.log('File uploaded');
            console.log(response);
            res.status(200).json({
                "done": "test complete"
            });
        }

    });    
}`

**Comment by sinkuu** [comment]
```javascript
const ipfs = require("ipfs-http-client")("http://localhost:5001");

const data = "";
const res = await ipfs.add([
    { path: "/" },
    { path: "/foo.txt", content: data }
]);
for await (const file of res) {
    console.log(file.cid.toString());
}
```

I expected this code creates a directory and an empty file inside, but it resulted in a directory and another directory inside. Is this really the intended behavior?

Anyway, I was able to workaround this problem by passing an empty array.

```javascript
const data = "";
const res = await ipfs.add([
    { path: "/" },
    { path: "/foo.txt", content: data || [] }
]);
```
