### ISSUE TITLE
js-api supporting for IPNS

### ISSUE THREAD

**Issue by riyazlafir** [ipfs/js-ipfs-api#517]
Hi ,

I want to  know is js-api support ipns ? if yes any one please let me know how to use api for IPNS.

thanks.

**Comment by diasdavid** [comment]
Not the best documentation, but one that works for sure, the tests! :) You can see it how it works here: 

https://github.com/ipfs/js-ipfs-api/blob/master/test/interface-ipfs-core/name.spec.js#L16-L70

**Comment by ylebre** [comment]
The url mentioned on Jan 29 isn't working anymore, the file can be found here:
https://github.com/ipfs/js-ipfs-api/blob/master/test/name.spec.js
