### ISSUE TITLE
reduce size of `ipfs.add` bundle and number of RPC requests.

### ISSUE THREAD

**Issue by slothbag** [ipfs/js-ipfs-api#522]
It appears the first request is to add the content, which we get a hash value returned.  But then it makes two more requests to get the data and links back.

Is there are a way to disable the last 2 requests?  I only need the hash.

Cheers

**Comment by diasdavid** [comment]
@slothbag I believe it only issues 2 requests, correct?

We could skip the second one if this https://github.com/ipfs/go-ipfs/issues/4008 comes to happen.

Now that https://github.com/ipfs/js-ipfs-api/pull/561 is happening, we will see a ton of bundle size reduction for `ipfs-api/add` if we can avoid that extra RTT

**Comment by diasdavid** [comment]
Now that https://github.com/ipfs/go-ipfs/pull/4082 has been merged and released, we can finish this up.

**Comment by diasdavid** [comment]
Now that the Dragon is gone (once released) https://github.com/ipfs/js-ipfsd-ctl/pull/165#issuecomment-327443185 I'll be able to PR for this issue in this issue :)

**Comment by diasdavid** [comment]
Seems that I was wrong, the feature required in go-ipfs is only going to be released in 0.4.11. Nevertheless, I went ahead and developed the PR for it once it gets released -> https://github.com/ipfs/js-ipfs-api/pull/595

Closing this one, let's track on the PR itself https://github.com/ipfs/js-ipfs-api/pull/595

**Comment by diasdavid** [comment]
Released with `v14.3.7` 🚀
