### ISSUE TITLE
browserify bundle too large and unable to be uglified

### ISSUE THREAD

**Issue by slothbag** [ipfs/js-ipfs-api#527]
I just went to build my application bundle and NUglify (C#) is unable to uglify the `js-ipfs-api` package, I have had no problem with the other dozen or so packages.

I also noticed the browserified package is 1.3Mb, that is large just to be able to post and retrieve some JSON to IPFS... Is there anyway to produce a lighter version?

**Comment by slothbag** [comment]
I just stumbled across this library which might do the trick.. https://www.npmjs.com/package/browser-ipfs

**Comment by dignifiedquire** [comment]
If you want to uglify it you will need to either transpile it to ES5 using something like babel, or use the harmony branch from UglifyJS as we do. The default installation of UglifyJS sadly does not have support for ES2015 yet.
