### ISSUE TITLE
Add pinning support for object.put

### ISSUE THREAD

**Issue by mitar** [ipfs/js-ipfs-api#532]
When calling object.put, it would be great if I could specify an option that the object should also be pinned. Currently it seems I have to do two calls. But I think it is pretty common that you want objects you created to be pinned on your instance of IPFS.

**Comment by diasdavid** [comment]
@whyrusleeping this would require first a change in go-ipfs. What's your take on it?

**Comment by diasdavid** [comment]
Please follow up on this issue with an issue on `go-ipfs`.
