### ISSUE TITLE
API difference to the cli i.e. omitting /ipfs/

### ISSUE THREAD

**Issue by thisconnect** [ipfs/js-ipfs-api#535]
Hi playing around with the js-ipfs-api and testing
`ipfs cat /ipfs/QmUwv8HhzNbsPreyUtK6Se4PnfTtSWiBdWdPhRMfRmsUAC`
reference https://github.com/ipfs/faq/issues/232#issuecomment-285661053

I get an error if the hash starts with `/ipfs/`

example

```js
api.add(Buffer.from('foo bar'))
  .then(result => api.name.publish(result[0].hash))
  .then(result => api.name.resolve(result.Name))
  .then(result => {
    console.log(result)
    return api.cat(result.Path) // remove /ipfs/ ??
  })
  .then(stream => stream.pipe(process.stdout))
```

error 
```
{ Path: '/ipfs/QmXho5iSk7YCNiqWWkM1UjuhSA4hphD7v5uTH9u1NKv2c3' }
Error: not valid multihash
    at module.exports (node_modules/ipfs-api/src/clean-multihash.js:14:11)
    at Function.err (node_modules/ipfs-api/src/api/cat.js:14:14)
    at Promise (node_modules/promisify-es6/index.js:43:20)
    at Object.cat (node_modules/promisify-es6/index.js:37:16)
    at api.add.then.then.then.result (index.js:14:16)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

Is it correct that I have to remove the `/ipfs/` of the beginning of the hash?
something like `api.cat(result.Path.split('/ipfs/')[1])`

docs: https://ipfs.github.io/js-ipfs-api/#ipfsapicat
api docs: https://ipfs.io/docs/commands/#ipfs-cat

**Comment by thisconnect** [comment]
ipfs-api@12.1.7
ipfsd-ctl@0.19.0
node v6.10.0
mac osx 10.12.3

**Comment by diasdavid** [comment]
Hi @thisconnect, thank you for bringing this up. We actually don't try to mimic the CLI library with js-ipfs-api, instead, we follow https://github.com/ipfs/interface-ipfs-core, the API spec for using IPFS programmatically.

That being said, your expectation has a very valuable point, and we actually can support it.

Would you like to own this change? Simply go to https://github.com/ipfs/interface-ipfs-core and

- Update the spec
- Write a test to make sure that is valid
- update js-ipfs and js-ipfs-api to support this new feature.

If you are busy or simply just not looking forward to contribute with this patch, that's ok, I'll try to handle as soon as I can :)

**Comment by thisconnect** [comment]
@diasdavid thanks for your quick response!!

I do not yet have a deep enough understanding on how ipfs works. For example I can't see any difference in `api.cat` vs. `api.files.cat`. At this point I am unsure if I could help with spec/test.

`api.files.cat` has tests, but I don't get where the code is coming from, shouldn't it be here https://github.com/ipfs/js-ipfs-api/blob/master/src/api/files.js ?

`api.cat` has no tests, should they have the same tests?
code lives here https://github.com/ipfs/js-ipfs-api/blob/master/src/api/cat.js

Found how cat is made available in files https://github.com/ipfs/js-ipfs-api/blob/e8c45f907832385c56aef11761a3998bdd708c7a/src/load-commands.js#L34-L42

**Comment by diasdavid** [comment]
`api.cat` is an alias of `api.files.cat` 😺

It has tests that are loaded from the tests bundle:
- Loads the tests https://github.com/ipfs/js-ipfs-api/blob/master/test/interface/files.spec.js
- ipfs.files tests https://github.com/ipfs/interface-ipfs-core/blob/master/src/files.js , where you have to add the extra test

**Comment by diasdavid** [comment]
This is now fixed and fully working. Documentation here: https://github.com/ipfs/interface-ipfs-core/tree/master/API/files#javascript---ipfsfilescatipfspath-callback

**Comment by thisconnect** [comment]
thanks!
