### ISSUE TITLE
Browserified API Works on Localhost but Not Deployed

### ISSUE THREAD

**Issue by chrismatthieu** [ipfs/js-ipfs-api#541]
I am building a client-side IPFS web app with the IPFS daemon running locally.  This API is browserified and works as expected when everything is running on localhost.  When web app is deployed on server and daemon is still running locally, I get the following ERR_Connection_Refused.  

My guess is that the browser app (when deployed on a domain - not localhost) cannot find the local daemon.  I do init the API as follows: var ipfs = IPFS('127.0.0.1') assuming that the browser could still find local IP address regardless of domain.  That does not work either. 

Could this issue be related to CORS?  Errors don't indicate CORs issues though...

127.0.0.1:5001/api/v0/swarm/peers?stream-channels=true Failed to load resource: net::ERR_CONNECTION_REFUSED

bundle.js:51 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at bundle.js:51
    at send (bundle.js:18267)
    at f (bundle.js:33980)
    at module.exports.req.on (bundle.js:19031)
    at module.exports.EventEmitter.emit (bundle.js:13803)
    at bundle.js:44227

**Comment by diasdavid** [comment]
@chrismatthieu that is a browser protection, a website can't dial to localhost ports, this would enable webapps to port scan your machine.

**Comment by sudeepshop** [comment]
@chrismatthieu did you solve your problem? I have a similar issue.
