### ISSUE TITLE
Trouble with base64 encoded buffers via browserified ipfsApi

### ISSUE THREAD

**Issue by ckeenan** [ipfs/js-ipfs-api#55]
Looking up a base64 encoded buffer works fine with the node ipfs-api module. In the browser, it appears there's a problem converting it to a string from Uint8Array. Here is some code that encounters this

```
var gifData = 'R0lGODlhAQABAIAAAAUEBAAAACwAAAAAAQABAAACAkQBADs=';

ipfsApi.add(new Buffer(gifData, 'base64'), function(err, ipfsArr) {
    if (err) throw err;

    ipfsApi.cat(ipfsArr[0].Hash, function(err, blobStr) {
      if (err) throw err;
      console.log('equal:', Buffer(blobStr, 'ascii').toString('base64') === gifData);   // false
    });
});
```

This change -- [https://github.com/ckeenan/node-ipfs-api/commit/0a9290a17e970b8a447cd0ba4b3a202693a1dcb5] -- resolves it, but unsure if best solution

**Comment by jbenet** [comment]
i think this is related to go-ipfs treatement of the buffers maybe. see https://github.com/ipfs/go-ipfs/issues/1582

**Comment by ckeenan** [comment]
That issue does affects this if there's going to be a change in the response format of `ipfs cat`.. but I think there's an unrelated issue here:

Running `ipfsApi.cat`, the http request for `ipfs cat` responds with a buffer. The browserified version appends the buffer's string `Uint8Array.prototype.toString()` to `''` which sometimes returns an incorrectly encoded string -- https://github.com/ipfs/node-ipfs-api/blob/master/src/request-api.js#L58. If buffers are the correct response type for api call to `ipfs cat`, the expected result could be achieved with `Buffer.concat()` or the Uint8Array can also be appened to `''` as a binary string.

Since ipfsApi.add expects a Buffer, seems reasonable for ipfsApi.cat to return Buffers? In which case maybe `Buffer.concat()` is the way to go

**Comment by jbenet** [comment]
thoughts @diasdavid @VictorBjelkholm @dignifiedquire @bcomnes ?

**Comment by diasdavid** [comment]
@ckeenan you definitely have a point, looking at that func it is hard to understand the reason on why that call. (+ things like https://github.com/ipfs/node-ipfs-api/blob/master/src/request-api.js#L77 and https://github.com/ipfs/node-ipfs-api/blob/master/src/request-api.js#L83-L84 suggest that we need to revisit it)

Now with the new documentation that @VictorBjelkholm is writing (https://github.com/ipfs/node-ipfs-api/issues/58), we should (or even must :)) write tests accordingly with the expectations of function calls to catch this cases.

**Comment by diasdavid** [comment]
@ckeenan we just added a considerable amount of tests to node-ipfs-api (https://github.com/ipfs/node-ipfs-api/pull/81) and landed the field for browser tests. Could you verify that the problem remains and if so, could you add a test case demonstrating the issue, so it is easier to target the fix? Thank you :)

**Comment by Dignifiedquire** [comment]
@ckeenan ping

**Comment by ckeenan** [comment]
@Dignifiedquire ACK. I am trying to test with a simple html file that includes `dist/ipfsapi.js` as a `<script />`. `ipfs.cat` returns a stream and not sure I can parse that in-browser. Is this expected?

**Comment by Dignifiedquire** [comment]
Yes this is expected, you can easily parse it like this:

```js
ipfs.cat('some hash', function (err, stream) {
  var res = ''

  stream.on('data', function (chunk) {
    res += chunk.toString()
  })

  stream.on('error', function (err) {
    console.error('Oh nooo', err)    
  })

  stream.on('end', function () {
    console.log('Got:', res)
  })
})
```

**Comment by ckeenan** [comment]
Oh excellent. So this lets the application concatenate the data any way it likes. That indeed fixes this issue where appending the stream's data arrays to an empty string can result in incorrect encodings for some types of buffers. Looks like this is ready to close @Dignifiedquire

**Comment by Dignifiedquire** [comment]
@ckeenan great to hear :)

**Comment by lekshmikbs123** [comment]
> Yes this is expected, you can easily parse it like this:
> 
> ```js
> ipfs.cat('some hash', function (err, stream) {
>   var res = ''
> 
>   stream.on('data', function (chunk) {
>     res += chunk.toString()
>   })
> 
>   stream.on('error', function (err) {
>     console.error('Oh nooo', err)    
>   })
> 
>   stream.on('end', function () {
>     console.log('Got:', res)
>   })
> })
> ```

I was trying this code and getting an error "stream.on is not a function" . Please help me out

**Comment by angelmariadas** [comment]
> Yes this is expected, you can easily parse it like this:
> 
> ```js
> ipfs.cat('some hash', function (err, stream) {
>   var res = ''
> 
>   stream.on('data', function (chunk) {
>     res += chunk.toString()
>   })
> 
>   stream.on('error', function (err) {
>     console.error('Oh nooo', err)    
>   })
> 
>   stream.on('end', function () {
>     console.log('Got:', res)
>   })
> })
> ```

I was trying this code and got an error "app.js:117564 Uncaught TypeError: stream.on is not a function
    at app.js:117564
    at BufferList.stream.pipe.bl [as _callback] (app.js:66091)
    at BufferList.end (app.js:59957)
    at exports.IncomingMessage.onend (app.js:106871)
    at exports.IncomingMessage.g (app.js:13053)
    at exports.IncomingMessage.EventEmitter.emit (app.js:12984)
    at endReadableNT (app.js:107304)
    at afterTickTwo (app.js:44809)
    at Item.run (app.js:2237)
    at drainQueue (app.js:2207)"

Please help me out

**Comment by lekshmikbs123** [comment]
> > Yes this is expected, you can easily parse it like this:
> > ```js
> > ipfs.cat('some hash', function (err, stream) {
> >   var res = ''
> > 
> >   stream.on('data', function (chunk) {
> >     res += chunk.toString()
> >   })
> > 
> >   stream.on('error', function (err) {
> >     console.error('Oh nooo', err)    
> >   })
> > 
> >   stream.on('end', function () {
> >     console.log('Got:', res)
> >   })
> > })
> > ```
> 
> I was trying this code and got an error "app.js:117564 Uncaught TypeError: stream.on is not a function
> at app.js:117564
> at BufferList.stream.pipe.bl [as _callback] (app.js:66091)
> at BufferList.end (app.js:59957)
> at exports.IncomingMessage.onend (app.js:106871)
> at exports.IncomingMessage.g (app.js:13053)
> at exports.IncomingMessage.EventEmitter.emit (app.js:12984)
> at endReadableNT (app.js:107304)
> at afterTickTwo (app.js:44809)
> at Item.run (app.js:2237)
> at drainQueue (app.js:2207)"
> 
> Please help me out

I was using ipfs version ^24.0.2, when I installed version 14.0.4 error just disappeared :)
