### ISSUE TITLE
iPad errors

### ISSUE THREAD

**Issue by edsilv** [ipfs/js-ipfs-api#558]
I'm getting errors when using js-ipfs-api in Safari on my iPad.

```
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
TypeError: undefined is not a function (evaluating 'window.IpfsApi()')
```

User agent:

```
Mozilla/5.0 (iPad; CPU OS 8_2 like Mac OS X)
AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0
Mobile/12D508 Safari/600.1.4
```

It looks like it doesn't like the `const` keywords and consequently `window.IpfsApi` isn't available?

Is there an ES5 transpiled version available on the CDN?

Here are the scripts I'm using:

```
<script src="https://unpkg.com/ipfs-api/dist/index.min.js"></script>
<script src="https://unpkg.com/ipfs/dist/index.min.js"></script>
```

The page breaks when I introduce this line:

`var Buffer = window.IpfsApi().Buffer;`

It also breaks in Chrome.

**Comment by diasdavid** [comment]
You will have to use [babel](https://babeljs.io/) to transpile ipfs-api into ES5 compatible code. There is a tutorial on how to do it on the babeljs page -- https://babeljs.io/docs/setup/#installation -- and you can use https://github.com/ipfs/js-ipfs-api/tree/master/examples/bundle-webpack as an example to set your Webpack config.
