### ISSUE TITLE
Allow the API server to run under the gateway

### ISSUE THREAD

**Issue by skorokithakis** [ipfs/js-ipfs-api#565]
I'm writing an IPFS app, where I wanted the flow to be like this:

* Fetch a page from the gateway.
* The page communicates with the gateway API and writes files.

Instead, I discovered that the API server runs on a different port, which means that the user has to both set up the CORS headers and that it's impossible for me to just autodiscover this if the user has changed the host or port.

This is a big hassle, and it would be much easier if the gateway itself had the API endpoints, so I could just use the API on the gateway from which the page was loaded. That way, applications running on IPFS wouldn't need CORS headers either, and their deployment would be many times easier (download and run the daemon, done).

**Comment by dryajov** [comment]
what do you mean by this:

>  and it would be much easier if the gateway itself had the API endpoints,

**Comment by skorokithakis** [comment]
I mean if the API were accessible under `http://localhost:8080/api/`.

**Comment by dryajov** [comment]
I wouldn't serve directly from the gateway, instead I'd use nginx or something else to proxy request. But even  then, I'd think hard before exposing http api to the app directly if its going to be served over a network (i.e. internet). I would also simply allow the app to be configurable as to where the api is pointed to currently. If the use knows how to change the default port, he/she should be able to adjust them in the app as well...

**Comment by diasdavid** [comment]
Appreciate the suggestion, @skorokithakis. We won't be able to fulfill that request, Gateway and API were designed with different purposes:

- Gateway is Read-Only and has things like a file explorer.
- API is Read+Write.

You don't need to set up CORS for the Gateway as it only supports GET requests.

**Comment by skorokithakis** [comment]
Yes, this was misguided, sorry. I later discovered the [IPFS gateway API](https://discuss.ipfs.io/t/writeable-http-gateways/210), which turned out to be what I wanted.

Given how much trouble I had finding it, though, I would *strongly* recommend linking it to some more visible section. It's a very useful API and I spent days of research without coming across it.
