### ISSUE TITLE
Add CI for Node.js and Browser tests

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs-api#57]

**Comment by VictorBjelkholm** [comment]
Starting looking into this, just got to this page before having other things to attend to: http://docs.travis-ci.com/user/gui-and-headless-browsers/ FYI

**Comment by harlantwood** [comment]
Circle CI is running tests, tried and failed to create a PR just now from my phone to add the status badge to the homepage:

[![Circle CI](https://circleci.com/gh/ipfs/node-ipfs-api.svg?style=svg)](https://circleci.com/gh/ipfs/node-ipfs-api)

Code: 

    [![Circle CI](https://circleci.com/gh/ipfs/node-ipfs-api.svg?style=svg)](https://circleci.com/gh/ipfs/node-ipfs-api)

**Comment by harlantwood** [comment]
...but perhaps this thread is suggesting we start running additional types of tests in CI...

**Comment by diasdavid** [comment]
Thank you @harlantwood , just PR'ed with the badged you added.

For browser tests CI, I was hoping to have something like:

![image](https://cloud.githubusercontent.com/assets/1211152/9903313/60ad4cc2-5c6d-11e5-8b3d-48850ad39cc5.png)

**Comment by harlantwood** [comment]
Ah!  Thanks for PR, and great idea!

**Comment by diasdavid** [comment]
Let's do this! https://github.com/ipfs/node-ipfs-api/pull/81

**Comment by diasdavid** [comment]
Following up on #81, we need to `Tweak timeouts so the tests pass on sauce labs every time`, so that we have CI browser tests on node-ipfs-api :) 

### API

- [x] before tests run
 - [x] start 3 disposable IPFS nodes, connect them in a triangle (needs: https://github.com/ipfs/node-ipfsd-ctl/issues/24 https://github.com/ipfs/node-ipfsd-ctl/pull/25)
- [x] .send
  - [x] node.js
  - [x] browser
- [ ] .add
  - [ ] .add a file
    - [x] node.js
    - [ ] browser
  - [ ] .add a buffer
    - [x] node.js
    - [ ] browser
  - [ ] .add a path
    - [x] node.js
    - [ ] browser
  - [ ] .add a folder (nested)
    - [x] node.js
    - [ ] browser
- [ ] .cat
  - [x] node.js
  - [ ] browser
- [ ] .ls
  - [x] node.js
  - [ ] browser
- [ ] .config
  - [ ] .config.get
    - [x] node.js
    - [ ] browser
  - [ ] .config.set
    - [x] node.js
    - [ ] browser
  - [ ] .config.show
    - [x] node.js
    - [ ] browser
  - [ ] .config.replace
    - [x] node.js
    - [ ] browser
- [ ] ~~.update~~ (Currently disabled, wait for version 0.4.0 release)
- [ ] .version
  - [x] node.js
  - [ ] browser
- [ ] .commands
  - [x] node.js
  - [ ] browser
- [ ] ~~.mount~~ (Requires FUSE, not practical for testing in node-ipfs-api)
- [ ] .diag
  - [ ] .diag.net
    - [x] node.js
    - [ ] browser
- [ ] .block
  - [ ] .block.get
    - [x] node.js
    - [ ] browser
  - [ ] .block.put
    - [x] node.js
    - [ ] browser
- [ ] .object
  - [ ] .object.get
    - [x] node.js
    - [ ] browser
  - [ ] .object.put
    - [x] node.js
    - [ ] browser
  - [ ] .object.data
    - [x] node.js
    - [ ] browser
  - [ ] .object.stat
    - [x] node.js
    - [ ] browser
  - [ ] .object.links
    - [x] node.js
    - [ ] browser
- [ ] .swarm
  - [ ] .swarm.peers
    - [x] node.js
    - [ ] browser
  - [ ] .swarm.connect
    - [x] node.js
    - [ ] browser
- [ ] .ping
  - [x] node.js
  - [ ] browser
- [ ] .id
  - [x] node.js
  - [ ] browser
- [ ] .pin
  - [ ] .pin.add
    - [x] node.js
    - [ ] browser
  - [ ] .pin.remove
    - [x] node.js
    - [ ] browser
  - [ ] .pin.list
    - [x] node.js
    - [ ] browser
- [x] ~~.gateway~~ this doesn't exist anymore on the http api
  - [x] ~~.gateway.enable~~
  - [x] ~~.gateway.disable~~
- [ ] log
  - [ ] log.tail (needs 0.3.9 ndjson stuff)
- [ ] .name
  - [ ] .name.publish
    - [x] node.js
    - [ ] browser
  - [ ] .name.resolve
    - [x] node.js
    - [ ] browser
- [ ] .Buffer (do we still need to expose Buffer? Node.js now uses TypedArrays, so it shouldn't be necessary)
  - [ ] node.js
  - [ ] browser
- [ ] .refs
  - [ ] .refs.local
    - [x] node.js
    - [ ] browser
- [ ] .dht
  - [ ] .dht.findprovs
    - [x] node.js
    - [ ] browser
  - [ ] .dht.get
    - [x] node.js
    - [ ] browser
  - [ ] .dht.put
    - [x] node.js
    - [ ] browser

**Comment by diasdavid** [comment]
This just got a huge boost with latest release (0.2.9) now we have tests passing on the browser, in CI! :D

**Comment by jbenet** [comment]
\o/

**Comment by Dignifiedquire** [comment]
Closing in favor of #170 which is all that's left to do :)
