### ISSUE TITLE
IPNS Support

### ISSUE THREAD

**Issue by Annorstades** [ipfs/js-ipfs-api#579]
Hi!

I was wondering if there is any documentation on interfacing with IPNS? I found an [old issue](https://github.com/ipfs/js-ipfs-api/issues/517) asking the same question, but the link in @diasdavid reply gives a 404. Any new info on this?

**Comment by diasdavid** [comment]
@Annorstades IPNS API is `ipfs name`, see: https://github.com/ipfs/js-ipfs-api#name

There is an example of how to use it: https://github.com/ipfs/js-ipfs-api/tree/master/examples/name-api

tests show more examples of it working: https://github.com/ipfs/js-ipfs-api/blob/master/test/name.spec.js

**Comment by VictorBjelkholm** [comment]
For future reference, these are David's links but with the commit instead so the URL will keep on working:

How to use: https://github.com/ipfs/js-ipfs-api/tree/0544dd378cf474c42a6f16626a83ac3bf5db9be2/examples/name-api

Tests: https://github.com/ipfs/js-ipfs-api/blob/0544dd378cf474c42a6f16626a83ac3bf5db9be2/test/name.spec.js

**Comment by diasdavid** [comment]
Thanks @VictorBjelkholm 

Closing this issue. @Annorstades let us know if you have any hurdles using it! :)
