### ISSUE TITLE
js-ipfs-api not compatible with the new go-ipfs name system (with multiple keys)

### ISSUE THREAD

**Issue by ReisenB** [ipfs/js-ipfs-api#582]
Recently go-ipfs got a cool upgrade where the daemon could maintain more than one IPNS address, and in my experience it seems to work quite well. However, js-ipfs-api does not yet support this new feature, and only has bindings for the old resolve and publish functions without allowing for the selection/creation of a different key.

**Comment by ReisenB** [comment]
I eventually got around to poking into the code and realize I was wrong: it _does_ in fact support this already, it's just not documented.

Here's how you generate a key:
```
ipfs.key.gen('MyNewKey', {type: 'rsa', size: '2048'}, (err, resp) => {
  if (err)
    console.log(err);
  console.log(resp);
});
```

And here's how you publish something to it:
```
ipfs.name.publish('/ipfs/Qmaaabbbcccblahblah', {key: 'MyNewKey'}, (err, resp) => {
  if (err)
    console.log(err);
  console.log(resp);
});
```

**Comment by diasdavid** [comment]
HI @ReisenB, mind writing an example on how to do this? 

Thank you for being a trooper and figuring it out :)
