### ISSUE TITLE
adding very small file

### ISSUE THREAD

**Issue by lockelost** [ipfs/js-ipfs-api#583]
Hi,
I tried add very small file (40 byte) with this 
https://github.com/ipfs/interface-ipfs-core/tree/master/API/files#add
but if I try to get this file with the result hash from my local machine, it gives me nothing.

But if I add the same text file from the shell prompt, with following command
> ipfs add ~/a.txt
it gives the same hash, and I can get the file.

Bigger files (over 256kb, as described in ipfs whitepaper) has no problem with that 'add' api.

Have any one of you noticed this, or am I the only one having this problem?

Thanks in advance.

**Comment by diasdavid** [comment]
Hi @brucewangkorea, this sounds like a bug, however, it is strange because we run tests with things as small as just 10 bytes strings.

Can you create a test that replicates this issue?

**Comment by diasdavid** [comment]
Closing given lack of response.
