### ISSUE TITLE
Bundle size updates

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/js-ipfs-api#584]
Currently js-ipfs-api creates bundle of 1.3MB (I might be wrong).
This means that it can be hardly used in websites as for its huge size. As it is supposed to be just a connector to go-ipfs/js-ipfs, is there a way to make it smaller?

**Comment by diasdavid** [comment]
@Kubuxu where are you getting that number? Depends on bow you are bundling it. It should be just ~660KB.

660KB is still big and that is why we pushed the endeavour of enabling modular support which was completed by @nunofmn. See submodule bundle sizes here:
https://github.com/ipfs/js-ipfs-api/blob/master/examples/sub-module/bundles-size-KBs.csv

**Comment by diasdavid** [comment]
Also, when this https://github.com/ipfs/go-ipfs/pull/4082 gets released, we will be able to complete https://github.com/ipfs/js-ipfs-api/issues/522

**Comment by diasdavid** [comment]
@Kubuxu ?

**Comment by Kubuxu** [comment]
It was information I was given on IRC. 600KB is much better yet it is still quite big.

There is also https://github.com/SilentCicero/ipfs-mini

**Comment by diasdavid** [comment]
Thanks for reminding me, @Kubuxu. I had in mind opening a issue on that module once the modularization of js-ipfs-api was done.

Issue opened now: https://github.com/SilentCicero/ipfs-mini/issues/6

**Comment by diasdavid** [comment]
Closing, let me know if this question is asked again.

**Comment by diasdavid** [comment]
It is going to get even smaller, @Kubuxu see: https://github.com/ipfs/js-ipfs-api/pull/595/commits/a5cb06e62dca0195eb2d5e8eb2b717ee47fce6af#r137276795
