### ISSUE TITLE
Unresolved link in README (Line 256-259)

### ISSUE THREAD

**Issue by PurgingPanda** [ipfs/js-ipfs-api#599]
The ipfs.name.* documentation has a link attached that points to a 404 page: https://github.com/ipfs/interface-ipfs-core/tree/master/API/name.

**Comment by diasdavid** [comment]
It doesn't exist yet. We should update that to not link anywhere, it might be confusing users.

@PurgingPanda if you are looking for how to use the .name API, check this example https://github.com/ipfs/js-ipfs-api/tree/master/examples/name-api hope it helps :)
