### ISSUE TITLE
add DAG api ?

### ISSUE THREAD

**Issue by thisconnect** [ipfs/js-ipfs-api#600]
Currently there is no DAG when using `js-ipfs-api` with a local go-ipfs daemon.

will dag be added in `js-ipfs-api`?

**Comment by atfornes** [comment]
I developed a branch to be able to use dags in js-ipfs-api. I believe it has not been merged because it does not allow protobuff nodes, but works for my needs: https://github.com/atfornes/js-ipfs-api/tree/withDag

It is a bit outdated and a rebase from master could be great.

**Comment by thisconnect** [comment]
Thanks for the reply I leave this issue open for now.

**Comment by diasdavid** [comment]
@thisconnect lots of work towards this here https://github.com/ipfs/js-ipfs-api/pull/534. Let's use the PR thread to keep discussing this.
