### ISSUE TITLE
Load js on iOS webkit

### ISSUE THREAD

**Issue by dominic-healid** [ipfs/js-ipfs-api#620]
Hey guys, does this API support iOS Webkit? I tried to load the html file to be able to run JS code through the iOS app but it doesn't seem to work. 

Any ideas or pointers?

**Comment by diasdavid** [comment]
@dominic-healid I confirmed that there is support for js-ipfs today (see https://twitter.com/daviddias/status/926430950183010309).

js-ipfs-api should work too. However, it is important to remember that you still need a remote node when using js-ipfs-api. This is just the http client https://github.com/ipfs/js-ipfs-api#--.
