### ISSUE TITLE
Recursive add on Windows

### ISSUE THREAD

**Issue by richardschneider** [ipfs/js-ipfs-api#637]
`js-ipfs` is adding extra folders when running on Windows.  Also the parent folder `test/fixtures/` should be removed from the output.

This was detected by the [refs.spec](https://github.com/ipfs/js-ipfs-api/blob/9ffe84803733eeab82cca2b8bec96c2ba1021d45/test/refs.spec.js) and discovered in [PR 636](https://github.com/ipfs/js-ipfs-api/pull/636)

 > node ..\js-ipfs\src\cli\bin.js add -r test\fixtures\test-folder
```
added QmbkMNB6rwfYAxRvnG9CWJ6cKKHEdq2ZKTozyF5FQ7H8Rs test/fixtures/test-folder/version
added QmctZfSuegbi2TMFY2y3VQjxsH5JbRBu7XmiLfHNvshhio test/fixtures/test-folder/ls
added QmU7wetVaAqc3Meurif9hcYBHGvQmL5QdpPJYBoZizyTNL test/fixtures/test-folder/ipfs-add
added QmafNdmKMjUPoAQLXtsjB5Q9DfRp5cVQY621gmyBGaYCyK test/fixtures/test-folder/hello-link
added QmdFyxZXsFiP4csgfM5uPu99AvFiKH62CSPDw5TP92nr7w test/fixtures/test-folder/files/ipfs.txt
added QmY9cxiHqTFoWamkQVkpmmqzBrY3hCBEL2XNu3NtX74Fuu test/fixtures/test-folder/files/hello.txt
added QmTYFLz5vsdMpq4XXw1a1pSxujJc9Z5V3Aw1Qg64d849Zy test/fixtures/test-folder/files
added QmNeHxDfQfjVFyYj2iruvysLH9zpp78v3cu1s3BZq1j5hY test/fixtures/test-folder/cat
added QmcUYKmQxmTcFom4R4UZP7FWeQzgJkwcFn51XrvsMy7PE9 test/fixtures/test-folder/add
added Qma8UM1iXpRjXJaG9PKxWzz9bnpruASGpLDKEy5cd5Apmz test/fixtures/test-folder
added QmQwGoVHMVMrQbZjDKkQqzDVgLXpe1NJ5FmGdmBB1FZVUM test/fixtures
added QmVZScPwqwp4e1VY5gYUMEc2g1LgcZdv9HoWSqTJuTYfWh test
```
> ipfs add -r test\fixtures\test-folder
```
 QmcUYKmQxmTcFom4R4UZP7FWeQzgJkwcFn51XrvsMy7PE9 test-folder/add
 QmNeHxDfQfjVFyYj2iruvysLH9zpp78v3cu1s3BZq1j5hY test-folder/cat
 QmY9cxiHqTFoWamkQVkpmmqzBrY3hCBEL2XNu3NtX74Fuu test-folder/files/hello.txt
 QmdFyxZXsFiP4csgfM5uPu99AvFiKH62CSPDw5TP92nr7w test-folder/files/ipfs.txt
 QmafNdmKMjUPoAQLXtsjB5Q9DfRp5cVQY621gmyBGaYCyK test-folder/hello-link
 QmU7wetVaAqc3Meurif9hcYBHGvQmL5QdpPJYBoZizyTNL test-folder/ipfs-add
 QmctZfSuegbi2TMFY2y3VQjxsH5JbRBu7XmiLfHNvshhio test-folder/ls
 QmbkMNB6rwfYAxRvnG9CWJ6cKKHEdq2ZKTozyF5FQ7H8Rs test-folder/version
added QmTYFLz5vsdMpq4XXw1a1pSxujJc9Z5V3Aw1Qg64d849Zy test-folder/files
added Qma8UM1iXpRjXJaG9PKxWzz9bnpruASGpLDKEy5cd5Apmz test-folder
```

**Comment by richardschneider** [comment]
There is a [related issue](https://github.com/ipfs/js-ipfs/issues/1079) on `ipfs ls`

**Comment by richardschneider** [comment]
The above should fix this issue.  But I can  not install `ipfsd-ctl` anymore (see https://github.com/ipfs/js-ipfsd-ctl/issues/177) and cannot proceed with testing. :(

**Comment by diasdavid** [comment]
Thank you @richardschneider. Seems that you opened this issue in the wrong repo (js-ipfs-api vs js-ipfs) but I got the memo that the fix is at https://github.com/ipfs/js-ipfs/pull/1108 and that you need https://github.com/ipfs/js-ipfsd-ctl/issues/177

**Comment by richardschneider** [comment]
Yes, I bug can crop up in one place, put is squashed in another place.

**Comment by diasdavid** [comment]
@richardschneider I didn't follow your last comment, could you rephrase?
