### ISSUE TITLE
Connect to Infura IPFS Node

### ISSUE THREAD

**Issue by FedericoCapello** [ipfs/js-ipfs-api#642]
Hi everyone, first, thank you for the amazing work.

I'm currently testing one of the sample apps provided (https://github.com/ipfs/js-ipfs-api/tree/master/examples/name-api) and I would like to use the Infura IPFS node, however, when I change this line:

`const ipfs = window.IpfsApi('/ip4/127.0.0.1/tcp/5001')`

to this line:

`const ipfs = window.IpfsApi('ipfs.infura.io', '5001', {protocol: 'https'})`

and try to publish a file it gives me first a warning:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ipfs.infura.io:5001/api/v0/name/publish?arg=QmZbj5ruYneZb8FuR9wnLqJCpCXMQudhSdWhdhp5U1oPWJ&stream-channels=true. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

and then an error:

> Error: XHR error
Stack trace:
IpfsApi</</ClientRequest.prototype._onFinish/xhr.onerror@https://unpkg.com/ipfs-api@17.2.4/dist/index.js:30117:23

How can I make it work with Infura? Thanks

**Comment by diasdavid** [comment]
@FedericoCapello sounds like that the Infura nodes do not have CORS enabled. This is not really up to the client library, it needs to be set up in the daemon. Learn more about it here: https://github.com/ipfs/js-ipfs-api#cors 

@kumavis @hermanjunge is there a reason why CORS is disabled on those nodes?

**Comment by hermanjunge** [comment]
Ping to @maurycyp and @egalano as they are running INFURA's Ferryman middleware.

**Comment by hermanjunge** [comment]
@diasdavid I re-issued the ticket in INFURA. So you can close this one.

**Comment by diasdavid** [comment]
@FedericoCapello seems like you got your call for support at the Infura project, follow up at https://github.com/INFURA/infura/issues/45

Thanks @hermanjunge :)

**Comment by FedericoCapello** [comment]
Thank you all

**Comment by jamesmorgan** [comment]
Seems to work on INFURA now see https://github.com/INFURA/infura/issues/45 👍
