### ISSUE TITLE
Uploading big files crush page in Chrome

### ISSUE THREAD

**Issue by mattermoran** [ipfs/js-ipfs-api#654]
So I'm doing as in this example https://github.com/ipfs/js-ipfs-api/tree/master/examples/upload-file-via-browser and everything works fine. But when I try to upload files that more than 3gb page crushes. 
![screen shot 2017-12-14 at 5 29 13 pm](https://user-images.githubusercontent.com/29712386/34324845-1615900c-e8bb-11e7-9245-448743bc334b.png)

**Comment by kostysh** [comment]
I am facing the same issue

**Comment by julientregoat** [comment]
I have the same issue, except with files over 50-100mb crashing it. I've tried ReadableStream, PullStream, buffer instances... nothing working. Smaller files get there just fine. Running node 8.10

**Comment by diasdavid** [comment]
@julientregoat -- https://github.com/ipfs/js-ipfs/issues/952 -- says that things are good uploading over 1GB on js-ipfs. Here, you are using js-ipfs-api, the HTTP Client library and talking with a go-ipfs daemon, it is a different scenario.

This should just be a buffering/streaming issue when creating the HTTP request. If anyone is available to tackle this, it would be great to have it solved.

**Comment by julientregoat** [comment]
@diasdavid ah got it! sorry, I didn't understand. still new to this but will try to play with it to see if I can get anything going.

**Comment by channprj** [comment]
It works on Safari. Just crashes in Chrome. How can I handle this? Does anybody work on it?

**Comment by diasdavid** [comment]
![](https://media.giphy.com/media/qIXVd1RoKGqlO/giphy.gif)
