### ISSUE TITLE
Configurable http.request protocol option

### ISSUE THREAD

**Issue by ckeenan** [ipfs/js-ipfs-api#66]
Running ipfs-api from an on-disk "file:///.../index.html" does not work. Calling http.request without passing a `protocol` in the opts, it will default to `window.location.protocol`. This causes the following error:
`TypeError: Failed to execute 'fetch' on 'Window': Failed to parse URL from file://127.0.0.1:5001/api/...`

see `dist/ipfsapi.js:5837`

Could we add a way to explicitly set this protocol option? It could be passed as an opt in the requestAPI or included as a param of IpfsAPI. The latter might be preferable for this scenario so not to require a protocol opt for every method.. maybe it could be IpfsAPI(host_or_multiaddr, port, opts)?

**Comment by jbenet** [comment]
Ahh i see. yeah we should.

**Comment by slothbag** [comment]
Same problem here. I pulled the protocol line out of ckeenans PR and was able to get it working, thanks ckeenan, would be great for this to be merged.

**Comment by xicombd** [comment]
Same problem here as well. 

I'm trying to run `ipfs-api` inside a chrome extension and need to specify the protocol, because it defaults to `chrome-extension://`.

**Comment by fmmartins** [comment]
:+1:

**Comment by Dignifiedquire** [comment]
Is this still an issue with the latest version? (We switched to `request` and pass `http` in the url)

**Comment by xicombd** [comment]
Yes, only could get it working when I [forced the protocol to `http`](https://github.com/xicombd/js-ipfs-api/commit/4a33fc688acc462a70e6939792bbdce8ca0a8234#diff-5993a3cf35b8b7b6d625694fcf2123f1R114).

**Comment by Dignifiedquire** [comment]
@xicombd okay thanks, strange though as I would expect request to take the protocol from the uri
