### ISSUE TITLE
Add files: progress options doesn't work

### ISSUE THREAD

**Issue by binhnd-socicom** [ipfs/js-ipfs-api#663]
I'm trying to get prgress when adding a big file as below

```
function addToIpfs(input) {
  function handler (p) { console.log(p); }
  ipfs.files.add(input, { progress: handler })
  .then(res => console.log(res))
  .catch(err => console.error(err))
}
```

It throws an error: **callback is not a function** as the callback now is pointing to options param.
If I remove the option, it works fine.

Am I make mistake somewhere?

**Comment by diasdavid** [comment]
@binhnd-socicom which version of js-ipfs-api are you using?

**Comment by binhnd-socicom** [comment]
@diasdavid Oh sorry. I found my mistake. I'm using version in **bundle-browserify** example as 11.2. 
It's ok now in latest version.

Thank you.

**Comment by ShareTheWorld** [comment]
@binhndicts  
@daviddias 
I have the same problem as you, this progress bar works slowly.
I add a file to ipfs via the add（） method, but I need to wait a long time before it call back the progress.
Just like the progress is called after the upload is completed.
Code
  Var file = files.files[0];
         Var ipfs = IpfsHttpClient({host: '95.179.200.133', port: '5001', protocol: 'http'});
          Var a = '';
          For (var i = 0; i < 500000; i++) a += 'aaaaaaaaaa';
         Const content = co.stringToBuffer(a);
         Ipfs.add(content, {
             Progress: function (p) {
                 Console.log(p);
             },
             chunkSize: 10 * 1024 * 1024
         }).then(function (result) {
             Console.log(result);
         }).catch(function (err) {
             Console.log(err);
         });

Can you give me an example of you?
