### ISSUE TITLE
addFromURL to support pinning, through `pin: true` option

### ISSUE THREAD

**Issue by olstenlarck** [ipfs/js-ipfs-api#674]
Probably most easier way is along these lines:

1. Change `const sendOneFile = SendOneFile(moduleConfig(arg), 'add')` to `let`

2. after the check of is valid url, add check for `opts.pin === true` and recreate `sendOneFile`

```js
    if (!validUrl(url)) {
      return callback(new Error('"url" param must be an http(s) url'))
    }
    if (opts.pin === true) {
        sendOneFile = SendOneFile(moduleConfig(arg), 'pin/add')
    }
    
    requestWithRedirect(url, opts, sendOneFile, callback)
```

**Comment by lidel** [comment]
I am not sure what is your goal here, to pin when `addFromURL` ?
AFAIK `ipfs.add` pins by  default already:

```
ipfs add --help | grep Pin
  --pin                              bool   - Pin this object when adding. Default: true.
```

**Comment by olstenlarck** [comment]
Hm. Didn't know that.
