### ISSUE TITLE
Install arise error,why? thanks

### ISSUE THREAD

**Issue by shishi614** [ipfs/js-ipfs-api#677]
mac system
192:ipfs-http-demo iinda$ npm install --save ipfs-api
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/dignifiedquire/webcrypto-shim.git
npm ERR! 
npm ERR! xcrun: error: active developer path ("/Applications/Xcode.app/Contents/Developer") does not exist
npm ERR! Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
npm ERR! See `man xcode-select` for more details.
npm ERR! 
npm ERR! exited with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lwy1218/.npm/_logs/2018-01-24T10_30_44_780Z-debug.log

**Comment by VictorBjelkholm** [comment]
Seems it wants you to try running `xcode-select --install` to install the command line developer tools.

**Comment by diasdavid** [comment]
@shishi614 you can find a helpful guide on how to get Node.js and npm set up at http://blog.teamtreehouse.com/install-node-js-npm-mac

That should solve your issue :)

**Comment by shishi614** [comment]
thanks,i  am installed well ,the reason is xcode is not install.
