### ISSUE TITLE
Sometimes ECONNRESET Error is thrown

### ISSUE THREAD

**Issue by mhhf** [ipfs/js-ipfs-api#69]
Only sometimes I get this error on `ipfs.ls(<hash>, cb )` and sometimes on `ipfs.pin`. In special when a set of executions is run.

```
I20151004-17:56:25.538(2)? catched error on ipfs ls { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
W20151004-17:56:25.539(2)? (STDERR) Possibly unhandled Error: read ECONNRESET
W20151004-17:56:25.539(2)? (STDERR)     at errnoException (net.js:905:11)
W20151004-17:56:25.539(2)? (STDERR)     at TCP.onread (net.js:559:19)
```

Any Idea what this could be?

**Comment by mhhf** [comment]
Apparently it is a nodejs problem. I'm using meteor which in it's lates version uses node 0.10.40 which causes this. With node 4.0.0+ everything seems fine.

The code I'm testing with: 
```
var ipfsApi = require('ipfs-api');
var ipfs = ipfsApi('localhost','5001');

for(var i=0; i<30; i++){
  ipfs.ls("QmPZWqn4ZRhGFJCTnNvaz3Wwe6inKQ4n6nJic4bAw3maz3", function(err,res) {
    if( err ) throw err;
  });
}
```

**Comment by diasdavid** [comment]
@mhhf I believe that is really a specific problem to Node.js 0.10 and 0.8, I've encountered, but it got fixed with 0.12 and onwards - http://blog.gluwer.com/blog.gluwer.com/2014/03/story-of-eaddrinuse-and-econnreset-errors/

**Comment by Dignifiedquire** [comment]
No it's not :( seeing the issue in electron, ref https://github.com/ipfs/station/issues/57 there the error is actually coming from `http.request`, so it might make sense to use a moduel with some better error handling like superagent instead of the raw `http.request`, but that's just a guess right now.

**Comment by diasdavid** [comment]
Interesting, so what does superagent do exaclty to fix the problem?

**Comment by Dignifiedquire** [comment]
@diasdavid I'm not a 100% sure, I think it has something to do with making sure that the correct headers are always like suggested in this [stackoverflow post](http://stackoverflow.com/questions/19810530/how-to-resolve-node-js-http-post-econnreset-error). But in general it felt much more stable and reliable when I was using it from station.

**Comment by diasdavid** [comment]
@Dignifiedquire fixed this on https://github.com/ipfs/js-ipfs-api/pull/92

@mhhf let me know if you still find this bug. Closing for now.

**Comment by Mukundan314** [comment]
I still have this error

Node version: v11.4.0
ipfs-http-client version: 28.0.0

error that I get:
```
{ Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:139:27) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
```
