### ISSUE TITLE
Getting CI green

### ISSUE THREAD

**Issue by vmx** [ipfs/js-ipfs-api#713]
This is a meta issue to collect all the PRs to get the CI Green

 - [x] https://github.com/ipfs/js-ipfs-api/pull/711
 - [x] https://github.com/ipfs/interface-ipfs-core/pull/235
 - [x] https://github.com/ipfs/interface-ipfs-core/pull/236
 - [ ] Fix of https://github.com/ipfs/interface-ipfs-core/pull/227#issuecomment-372696424
 - [ ] https://github.com/ipfs/jenkins/issues/95
 - [ ] Fix of https://github.com/ipfs/js-ipfs-api/issues/715
 - [x] https://github.com/ipfs/interface-ipfs-core/pull/238
 - [x] https://github.com/ipfs/js-ipfs-api/pull/716
 - [x] https://github.com/ipfs/interface-ipfs-core/pull/239

**Comment by diasdavid** [comment]
@vmx double check, but I think you also need https://github.com/ipfs/js-ipfs-api/pull/695

**Comment by vmx** [comment]
@diasdavid So far it doesn't seem that I need #695, except if it fixes https://github.com/ipfs/interface-ipfs-core/pull/227 (i haven't tried yet)

**Comment by vmx** [comment]
With the outstanding PRs merged and these three reverted:

 - https://github.com/ipfs/js-ipfs-api/commit/a10e3d57f0d71e934faa26ba63d371edcd86df92
 - https://github.com/ipfs/js-ipfs-api/commit/b08f21a8dea1852064518d045cf17706bf90b821
 - https://github.com/ipfs/interface-ipfs-core/commit/de72184d45aab5153818d96e6d0d3b38ea8b6076

CI is quite often green. It's still not reliable, but as different tests are failing I'd consider them environment issues.

**Comment by vmx** [comment]
@diasdavid Everything from my side is merged now. The test runs are quite stable now. Now only the tests broken by the commits mentioned above need to be fixed. Who will fix those? The authors of those commits?

**Comment by diasdavid** [comment]
@vmx would you have the chance to fix those too? thanks!

**Comment by vmx** [comment]
@diasdavid Not sure when, but I can have a look if it isn't fixed in the meantime.

**Comment by diasdavid** [comment]
@vmx I went through it. the files.stat was failing because it was expecting features that haven't been released on go-ipfs. ALl good now :)

**Comment by vmx** [comment]
Thanks David for fixing those! I'm looking forward to have js-ipfs-api green *fingerscrossed*.
