### ISSUE TITLE
Error passing a filepath string to files.add

### ISSUE THREAD

**Issue by olizilla** [ipfs/js-ipfs-api#722]
The interface spec suggests that from node you can call `ipfs.add` with a Path.
https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md#add

>` ipfs.files.add(data, [options], [callback])`
Where `data` may be:
> a Buffer instance
a Readable Stream
a Pull Stream
**a Path (caveat: will only work in Node.js)**
a URL
an array of objects

Trying to pass a file system path as a string throws an error

```
Error: first arg must be a buffer, readable stream, an object or array of objects
    at Function.promisify (/Users/oli/Code/ipfs/js-ipfs-api/src/files/add.js:34:23)
    at Object.add (/Users/oli/Code/ipfs/js-ipfs-api/node_modules/promisify-es6/index.js:32:27)
    at Object.<anonymous> (/Users/oli/Code/ipfs/js-ipfs-api/examples/files-api/files-api.js:19:12)
```

Do I need to update the spec, or fix the implementation?

**Comment by diasdavid** [comment]
The plan was to merge add, addFromUrl and addFromFs into just add with -- https://github.com/ipfs/interface-ipfs-core/pull/162#issue-148011840 -- endeavor, that last bit was postponed and didn't get done.

What this means is that, yes the docs are wrong for the current implementation but what we would like is to improve the implementation to actually support it. Thanks @olizilla for catching this one :)
