### ISSUE TITLE
ping tests on Windows fail a lot

### ISSUE THREAD

**Issue by vmx** [ipfs/js-ipfs-api#725]
Probably due to https://github.com/ipfs/js-ipfs-api/pull/718 the ping tests on Windows got flaky:

 - https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs-api/detail/master/61/tests
 - https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs-api/detail/master/62/tests
 - https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fjs-ipfs-api/detail/master/63/tests

**Comment by VictorBjelkholm** [comment]
Quick fix would be to add logic in the test to be able to flag a test as "flaky" and if it has that tag, retry it X times before actually failing.

**Comment by alanshaw** [comment]
Windows tests have consistently failed since https://github.com/ipfs/js-ipfs-api/commit/427322d8ed0a8833854ab42d50acf05676cfe969 when we switched to `go-ipfs-dep@0.4.14`.

**Comment by alanshaw** [comment]
Looks like there _is_ a peer discovery regression on Windows. I've opened https://github.com/ipfs/go-ipfs/issues/5146

**Comment by alanshaw** [comment]
This was resolved by https://github.com/ipfs/interface-ipfs-core/pull/311
