### ISSUE TITLE
Cannot use files.write api

### ISSUE THREAD

**Issue by maitrungduc1410** [ipfs/js-ipfs-api#736]
Hi everyone,
I have an issue and try to fix it but nothing works.
I upload a file using files.write.api. but everything it throws an error: 'file does not exist' (see in picture below)
above the error, I log the buffer of file I want to upload, it looks ok, but the api doesn't work.
Try to find another example but I couldn't find out anything even in this repository
If anyone has this problem before, can you help me?
thank you!
p/s: I also attach a bunch of my code which log the buffer and make api
[
<img width="1440" alt="screen shot 2018-04-12 at 11 10 00 am" src="https://user-images.githubusercontent.com/16630193/38656061-5e64565e-3e42-11e8-8041-b779c276f1f7.png">
](url)
<img width="467" alt="screen shot 2018-04-12 at 11 13 07 am" src="https://user-images.githubusercontent.com/16630193/38656085-82872354-3e42-11e8-9b5b-dfb27dd68f94.png">

**Comment by VictorBjelkholm** [comment]
What is `path` in this scenario? MFS doesn't automatically create the paths so if path is `/my-directory/my-file`, you would need to create `/my-directory` before you can write to `/my-directory/my-file`. You also need to add the `--write` flag if the file does not exists since before.

**Comment by maitrungduc1410** [comment]
How lucky with your help, I add option {create:true} in case of the file doesn't exist and it works, thank you so much!

**Comment by VictorBjelkholm** [comment]
Great to hear! :+1: (sorry for the confusion with `--create`, you're correct with it being `{create: true}` instead)
