### ISSUE TITLE
Use js-ipld for DAG API

### ISSUE THREAD

**Issue by vmx** [ipfs/js-ipfs-api#738]
Basic support for the DAG API landed with https://github.com/ipfs/js-ipfs-api/pull/534.

Though not all formats are supported and you can't traverse through different types of formats. I.e. you couldn't follow a link from a dag-cbor node to a dag-pb node.

The solution is to use js-ipld instead of hard-coding the formats (currently dag-cbor and dag-pb).

Using js-ipld is not straight forward. The problem is that js-ipld needs a Block Service which in turn needs a Repository to work. But js-htt-api doesn't have the blocks available in the JS environment, but receives them manually over the HTTP API.

So I guess you would need a Block Service (or Repository) that uses the HTTP API to retrieve the blocks. But I leave the details to whoever will implement this.

**Comment by alanshaw** [comment]
If no-one else is working on this I'd like to have a stab at it. We need the DAG API to work properly for the IPLD Explorers to work with JS-IPFS.

I'm thinking create an `IPLDResolver` with a block service that uses an "API exchange" (a bitswap exchange that just uses the `block` API to retrieve blocks it doesn't have).

At least, from reading the commentary on #534 that seems to be the idea.

Any objections?

**Comment by alanshaw** [comment]
Is it as simple as this? I added IPLD to `js-ipfs-api` and it now `dag.get` **git** dags 😮 

<img width="1280" alt="screen shot 2018-05-01 at 20 24 52" src="https://user-images.githubusercontent.com/152863/39489626-1f5aa86e-4d7e-11e8-84ae-1e1312ba8b30.png">

**Comment by diasdavid** [comment]
Woot! Great work @alanshaw ❤️ Let's finish this feat convo up on https://github.com/ipfs/js-ipfs-api/pull/755
