### ISSUE TITLE
IPFS and Blockchain. What is the benefit?

### ISSUE THREAD

**Issue by maitrungduc1410** [ipfs/js-ipfs-api#739]
I read on the landing page ipfs.io. it says: "IPFS and the Blockchain are a perfect match! You can address large amounts of data with IPFS, and place the immutable, permanent IPFS links into a blockchain transaction. **This timestamps and secures your content**, without having to put the data on the chain itself."
I don't know why it can secure my content. And is that any other benefit when I use IPFS with blockchain?
If anyone knows may you explain me?
Many thanks!!!!

**Comment by vmx** [comment]
For general questions we also have a forum at https://discuss.ipfs.io/. There is a bigger active crowd than on this issue tracker, so you might have better chance getting your questions answered there.

**Comment by VictorBjelkholm** [comment]
@maitrungduc1410 already created a topic on our forum, so let's continue there: https://discuss.ipfs.io/t/ipfs-and-blockchain-what-is-the-benefit/2672
