### ISSUE TITLE
Check if source file exist during (or before) pin it

### ISSUE THREAD

**Issue by evildido** [ipfs/js-ipfs-api#752]
Hi.

I'm currently developing a bot that collect video content (hash) on the steem blockchain. 
In some case, the content doesn't have a seed and connot be pinned. 

I'm searching a way to detect that the content cannot be pinned.
Do you have any ideas ?

Thx

**Comment by VictorBjelkholm** [comment]
It's hard to know with exact certainty if you can get the content or not. One thing you can try is to call `dht.findprovs(hash)` and it'll return the peers that say they have the content. If it returns below X amount of peers, assume that the content is non-gettable.

**Comment by evildido** [comment]
oh great. I see findprovs timeout if no peer has the content.
it could be cool to have the same for timeout pin add.

**Comment by alanshaw** [comment]
Closing as I think that answers your question @evildido :D
