### ISSUE TITLE
 at exports._exceptionWithHostPort (util.js:1049:20)     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)   code: 'ETIMEDOUT',   errno: 'ETIMEDOUT',   syscall: 'connect',

### ISSUE THREAD

**Issue by blockChainB** [ipfs/js-ipfs-api#753]
const ipfs = ipfsAPI('lfx.imcia.com',"8080", {protocol: 'http'})
console.log(ipfs);
return;
const buffer = Buffer.from('this is a my  demo')
ipfs.add(buffer)
    .then( rsp => console.log(rsp[0].hash))
.catch(err => console.error(err))

return a error  

 at exports._exceptionWithHostPort (util.js:1049:20)     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)   code: 'ETIMEDOUT',   errno: 'ETIMEDOUT',   syscall: 'connect',

https://lfx.imcia.com:8080/ipfs/QmNroiDmtFiyCUmCqVvnMTYKbu8R2tRmZ6JubpiidJKQ3b  is  work
why this cannot work ? 
thanks

**Comment by alanshaw** [comment]
hey @blockChainB if you want to use the API to talk to your IPFS node you'll need to connect to port 5001 (by default). Port 8080 is the gateway port, for accessing IPFS content over HTTP.

See https://github.com/ipfs/js-ipfs-api#running-the-daemon-with-the-right-port for more info.

Hope that helps!
