### ISSUE TITLE
When i try to publish a IPNS name on Travis Ci i get this Error: failed to find any peer in table

### ISSUE THREAD

**Issue by lukas2005** [ipfs/js-ipfs-api#759]
Full error:
```
{ Error: failed to find any peer in table
    at parseError (/home/travis/build/Decentracord/Decentracord-Web/node_modules/ipfs-api/src/utils/send-request.js:16:17)
    at ClientRequest.<anonymous> (/home/travis/build/Decentracord/Decentracord-Web/node_modules/ipfs-api/src/utils/send-request.js:39:14)
    at Object.onceWrapper (events.js:272:13)
    at ClientRequest.emit (events.js:180:13)
    at HTTPParser.parserOnIncomingClient (_http_client.js:539:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at Socket.socketOnData (_http_client.js:444:20)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11) code: 0 }
```
Repo: https://github.com/Decentracord/Decentracord-Web
Deploy script: https://github.com/Decentracord/Decentracord-Web/blob/master/app/deploy.js
Travis Log: https://travis-ci.org/Decentracord/Decentracord-Web/builds/376512233#L1514

**Comment by alanshaw** [comment]
hey @lukas2005 did you resolve this issue?

It looks to me like that error would occur when the IPFS node cannot find any peer with the hash you pass to `name.publish`. By default it ensures it exists before publishing:

https://github.com/ipfs/go-ipfs/blob/3f6519b420f0793aa4995b3773e55e3277c8a11f/core/commands/publish.go#L174

Maybe this is an issue with the Travis environment?

**Comment by lukas2005** [comment]
I have no idea if that's true but maybe? I just have no idea what in the Travis env would cause such a issue

**Comment by lukas2005** [comment]
Hmm ill add that info tomorrow and yeah i know i plan on setting up ipfs on my RPI 3 and on users machine if they use my electron app (it loads my web app from IPFS)

**Comment by lukas2005** [comment]
go-ipfs version is: 0.4.14 (added using a npm package go-ipfs-dep (specified in package.json))
And when i tried modifying the publish code to this:
```
	ipfs.swarm.peers((err, peerInfos) => {
		console.log(peerInfos);

		ipfs.name.publish(hash, { key: key.name }, (err, name) => {
			if (err) {
				console.error(err);
			} else {
				console.log("The published IPNS name is: "+name.name);
				console.log("and it resolves to: "+name.value);
			}
			callback();
		});	
	});
```
My travis build just timeouts: https://travis-ci.org/Decentracord/Decentracord-Web/builds/378301249

**Comment by lukas2005** [comment]
Hmm so i guess i should wait some time to let ipfs to connect to peers?

**Comment by alanshaw** [comment]
We'll have a new version of ipfs-api out soon to fix that issue but until then try waiting some time before calling `name.publish` so your node can connect to peers.

I'm going to close this issue in the hope that that fixes your issue. Please comment here again if not and I'll re-open.
