### ISSUE TITLE
example/upload_file_via_browser

### ISSUE THREAD

**Issue by sravanthbaratam** [ipfs/js-ipfs-api#766]
after npm install 
npm start 
`ERROR in /Users/sravanthbaratam/js-ipfs-api/src/utils/default-config.js
Module not found: Error: Cannot resolve module 'json-loader' in /Users/sravanthbaratam/js-ipfs-api/src/utils
 @ /Users/sravanthbaratam/js-ipfs-api/src/utils/default-config.js 3:12-41

ERROR in /Users/sravanthbaratam/js-ipfs-api/~/browserify-aes/browser.js
Module not found: Error: Cannot resolve module 'json-loader' in /Users/sravanthbaratam/js-ipfs-api/node_modules/browserify-aes
 @ /Users/sravanthbaratam/js-ipfs-api/~/browserify-aes/browser.js 3:12-40

ERROR in /Users/sravanthbaratam/js-ipfs-api/~/fs-constants/browser.js
Module not found: Error: Cannot resolve module 'json-loader' in /Users/sravanthbaratam/js-ipfs-api/node_modules/fs-constants
 @ /Users/sravanthbaratam/js-ipfs-api/~/fs-constants/browser.js 1:17-37

ERROR in /Users/sravanthbaratam/js-ipfs-api/~/browserify-aes/modes/index.js
Module not found: Error: Cannot resolve module 'json-loader' in /Users/sravanthbaratam/js-ipfs-api/node_modules/browserify-aes/modes
 @ /Users/sravanthbaratam/js-ipfs-api/~/browserify-aes/modes/index.js 12:12-34

ERROR in /Users/sravanthbaratam/js-ipfs-api/~/secp256k1/lib/index.js
Module not found: Error: Cannot resolve module 'json-loader' in /Users/sravanthbaratam/js-ipfs-api/node_modules/secp256k1/lib
 @ /Users/sravanthbaratam/js-ipfs-api/~/secp256k1/lib/index.js 4:15-41

ERROR in /Users/sravanthbaratam/js-ipfs-api/~/secp256k1/lib/js/index.js
Module not found: Error: Cannot resolve module 'json-loader' in /Users/sravanthbaratam/js-ipfs-api/node_modules/secp256k1/lib/js
 @ /Users/sravanthbaratam/js-ipfs-api/~/secp256k1/lib/js/index.js 5:15-42

ERROR in /Users/sravanthbaratam/js-ipfs-api/~/drbg.js/hmac.js
Module not found: Error: Cannot resolve module 'json-loader' in /Users/sravanthbaratam/js-ipfs-api/node_modules/drbg.js
 @ /Users/sravanthbaratam/js-ipfs-api/~/drbg.js/hmac.js 3:15-46
webpack: Failed to compile.
`

**Comment by alanshaw** [comment]
@sravanthbaratam did you get any errors when you did your `npm install`? `json-loader` is [listed as a dependency](https://github.com/ipfs/js-ipfs-api/blob/faa51b4c26abc047fd94b78535e77ca2dc95630f/examples/upload-file-via-browser/package.json#L17).

**Comment by alanshaw** [comment]
I've just installed and ran the example and it works fine for me, note that you have to cd into the example directory before running `npm install` e.g.

```sh
cd examples/upload-file-via-browser
npm install
npm start
```

**Comment by sravanthbaratam** [comment]
@alanshaw no errors with npm install 
Json loader is listed in dependency
I changed the directory to upload file via browser folder where the package.json file is there.

**Comment by alanshaw** [comment]
Could you tell me your Node.js and npm version and OS?

**Comment by sravanthbaratam** [comment]
@alanshaw 
npm -v
6.0.1
node -v
v8.10.0
macos high sierria 10.13.4

**Comment by alanshaw** [comment]
Ah, I know the answer, the example [overrides the ipfs-api dependency to point at the project root](https://github.com/ipfs/js-ipfs-api/blob/master/examples/upload-file-via-browser/package.json#L16). That means that you **also** need to run `npm install` in the project root.

So the steps should be:

```
git clone https://github.com/ipfs/js-ipfs-api.git
cd js-ipfs-api
npm install
cd examples/upload-file-via-browser
npm install
npm start
```

Please try that and let me know if it doesn't solve your issue.

**Comment by sravanthbaratam** [comment]
@alanshaw 
i got this after first npm install

WARN tar ENOENT: no such file or directory, open '/Users/sravanthbaratam/js-ipfs-api/node_modules/.staging/libp2p-webrtc-star-05883b38/dist/index.js.map'
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:563:10)
    at ReadEntry.entry.on (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
    at Unzip.(anonymous function).on.chunk (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/usr/local/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
WARN tar ENOENT: no such file or directory, open '/Users/sravanthbaratam/js-ipfs-api/node_modules/.staging/ipld-dc9795a9/dist/index.js.map'
WARN tar ENOENT: no such file or directory, open '/Users/sravanthbaratam/js-ipfs-api/node_modules/.staging/ipld-zcash-e93990a3/dist/index.js.map'

**Comment by alanshaw** [comment]
Try removing your `node_modules` folder in the root and the example directory and start again from scratch.
