### ISSUE TITLE
ipfs.add should always return same type

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/js-ipfs-api#79]
`ipfs.add` have a kind of confused API (the same with some other methods), that it's sometimes returning a stream and sometimes an object. I think this is because of the environment but we should try to make sure that inside the callback, users don't have to try to figure out what type it is, it should always be the same type.

Will also help simplifying the tests for browser/node environments.

**Comment by Dignifiedquire** [comment]
:+1:

**Comment by VictorBjelkholm** [comment]
I see now that `ipfs.add` is not the only command that works this way. `ipfs.object.data`, `ipfs.cat` and `ipfs.block.get` would need to be fixed as well.

**Comment by diasdavid** [comment]
with the update to 0.3.8, IPFS started returning ndjson on the HTTP API instead of a JSON array, we need to update that on the node-ipfs-api

**Comment by diasdavid** [comment]
@VictorBjelkholm can you confirm if this is still a problem this? The distinction between a stream and an object comes from go-ipfs itself, depending how the header is set:

https://github.com/ipfs/js-ipfs-api/blob/master/src/request-api.js#L63-L64

**Comment by Dignifiedquire** [comment]
According to the tests this should now happen, and will be available for everyone when https://github.com/ipfs/go-ipfs/issues/1979 is merged and released. @VictorBjelkholm can you confirm please?
