### ISSUE TITLE
Is it possible to reference a hash when adding files?

### ISSUE THREAD

**Issue by mallendeo** [ipfs/js-ipfs-api#791]
Is there a way to calculate the `cid` and append it to the current upload?

e.g:

```js
const files = [
  { path: '/src/index.html', content: new Buffer('...') },
  'ipfs/QmQiRTT6MYUPATjG...'  // existing file
]

await ipfs.files.add(files, { wrapWithDirectory: true, pin: true })
```

**Comment by lidel** [comment]
AFAIK no: `content` needs to be a Buffer, Readable Stream or Pull Stream with the contents of the file.

_However,_ you can use [`ipfs.object.patch.addLink(multihash, link, [options, callback])`](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/OBJECT.md#objectpatchaddlink) to add a new file using any CID to any directory and get a new CID in return:

```js
// QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn is an empty directory
// QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR is a file you want to add to it
ipfs.object.patch.addLink('QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn', {
  name: 'persian-room-guardian.jpg',
  multihash: 'QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR'
}, (err, newNode) => {
  if (err) {
    throw err
  }
  console.log(newNode.toJSON().multihash)
  // QmRAJM5ByzuKKpzKKisGDwBPHzYqMvVrYC2PcVhkMnP3gd is a directory with the added link
})
```

**Comment by mallendeo** [comment]
Thanks @lidel!

[QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR](https://ipfs.infura.io/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR) nice meme btw
