### ISSUE TITLE
Mixed Content issue while adding file to ipfs

### ISSUE THREAD

**Issue by yashwanth2804** [ipfs/js-ipfs-api#814]
request.js:119 Mixed Content: The page at 'https://myrepo.github.io/iop/index3.html' was loaded over HTTPS, but requested an insecure resource 'http://myip:5001/api/v0/add?recursive=true&stream-channels=true'. This request has been blocked; the content must be served over HTTPS.

**Comment by alanshaw** [comment]
Hi @yashwanth2804,

Resources served from a secure context cannot make AJAX requests to insecure contexts. This is a browser restriction and not an issue with js-ipfs-api.

You'll need to access your IPFS API over HTTPS if your want https://myrepo.github.io/iop/index3.html to be allowed to talk to it. Commonly people run an nginx or apache server as a TLS termination proxy to the API.

Alternatively you can just use js-ipfs directly in the browser.

Hope that helps!
