### ISSUE TITLE
Can't install ipfs-api. Command“npm install --save ipfs-api” don't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by nineblu** [ipfs/js-ipfs-api#818]
after i input command "npm install --save ipfs-api", it is stopping at "loadDep:webcrypto-shim" and the progress bar don't move any longer. 
Just like this: [https://ipfs.io/ipfs/QmRFhvQZBfHBDfHQwwJzixgr3oG7nwftusxufHWukbtdUQ](url)
![ax](https://user-images.githubusercontent.com/24690674/43033531-73dc10ac-8cfe-11e8-8c8b-d0404f9a2da1.jpg)

Could anyone help to solve this problem? Thanks very much!

**Comment by alanshaw** [comment]
Do you have git installed? Looks like a dependency depends on a git repo that npm needs to clone.

**Comment by nineblu** [comment]
Yep, I have git installed successfully. But maybe it's my network's problem rather than git. And now it works!

**Comment by alanshaw** [comment]
\o/
