### ISSUE TITLE
Error: Can't resolve 'async/eachSeries'

### ISSUE THREAD

**Issue by kasperfish** [ipfs/js-ipfs-api#829]
I'm trying to use the ipfs-api with vue/quasar. I think this is a webpack error but don't know how to solve it.
![image](https://user-images.githubusercontent.com/5130772/44001112-01e0f3f2-9e2c-11e8-9251-d4d5a59a11e7.png)

**Comment by alanshaw** [comment]
I'm not sure if I can help with this - I've double checked `async` is a dependency and with a fresh install of `ipfs-api` I can see `node_modules/async/eachSeries.js`. So, I don't think this is an issue with `ipfs-api`...have you tried removing your `node_modules` and `package-lock.json` and re-installing?
