### ISSUE TITLE
Doesn't work inside a service-worker on Firefox

### ISSUE THREAD

**Issue by koalalorenzo** [ipfs/js-ipfs-api#848]
By playing around with `js-ipfs-api` inside a service worker, I have noticed that it works perfectly on Safari and Chrome, but apparently not on Firefox. 

The error reported is related to the usage of `XMLHTTPRequest`.

I guess this is the cause: https://www.fxsitecompat.com/en-CA/docs/2015/xmlhttprequest-is-no-longer-available-in-service-workers/

Any guess how to solve/fix this to support also Firefox service workers?

**Comment by koalalorenzo** [comment]
I will try to find the time for it 👍 

Should I update it for all the requests? I was diving a little and I found this line:
https://github.com/ipfs/js-ipfs-api/blob/231c4d78723d41152e6a695a5f171feae2274c19/src/utils/send-request.js#L174

That connects to: 
https://github.com/ipfs/js-ipfs-api/blob/master/src/utils/request.js

I see from the code that there is a lot of dependency on how we are using this module. I guess I need to change that. 

In any case can you guide a little bit me to find what would be the best solution? Maybe also @alanshaw can give me some suggestion _a la planning_ 😃

**Comment by vasco-santos** [comment]
Nice research! 

I believe that we should have `fetch` for every single request, since each api call should be accessible through a `service worker` as well.

Yes, I suppose it will not be an immediate and easy change, as you say, some of the request's building blocks have to be implemented according to the fetch API. Let's wait for @alanshaw input here.

**Comment by hugomrdias** [comment]
In the browser we use `stream-http` package that is suppose to use fetch if it's available we should report this problem to them

**Comment by shunkino** [comment]
HI @koalalorenzo, I think this is because `ReadableStream()` is disabled in Firefox by default.
This function should be available for `stream-http` to work as a fetch() mode.

Could you test your code after enabling `ReadableStream()` by procedure below?

https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream
```
From version 57: this feature is behind the dom.streams.enabled preference (needs to be set to true) and the javascript.options.streams preference (needs to be set to true). To change preferences in Firefox, visit about:config.
```

**Comment by koalalorenzo** [comment]
The error that I am getting when I am doing a simple list of pinned elements is reporting a `XMLHTTPRequest` so I am not sure how much that is related to `ReadableStream`, but I could be wrong.  

<img width="472" alt="screen shot 2018-09-10 at 09 06 47" src="https://user-images.githubusercontent.com/33528/45281704-eb64fd80-b4d8-11e8-9d5a-5f38c4e2dea8.png">

https://www.fxsitecompat.com/en-CA/docs/2015/xmlhttprequest-is-no-longer-available-in-service-workers/

**Comment by koalalorenzo** [comment]
Enabling ReadableStream on Firefox it doesn't fix the problem.

**Comment by hugomrdias** [comment]
I'm looking into stream-http for other stuff I'll check this out.

**Comment by jhiesey** [comment]
@hugomrdias let me know if you need help with `stream-http`. I'm the maintainer of that module and also working for Protocol Labs.

**Comment by koalalorenzo** [comment]
Can anybody explain to me why it is `stream-http` the cause of this?

**Comment by shunkino** [comment]
It's because js-ipfs-api uses `stream-http` as an alternative of `http` in browser environment.
https://github.com/ipfs/js-ipfs-api/blob/master/package.json#L11

**Comment by shunkino** [comment]
@koalalorenzo 
Hi again, sorry for sending comments frequently. Thank you for testing my previous post. Sorry to hear that it didn't worked out for you. 😢 

I just tested ServiceWorker inside Firefox and was able to call `ipfs.pin.ls()` from it. My environment: Firefox (Quantum 61.0.2 on MacOS). Only change I did is enabling `ReadableStreaming()`

This is the screenshot of my console.
![image](https://user-images.githubusercontent.com/7201054/45288711-496c0200-b526-11e8-85bc-b7485f14a549.png)
Sorry for random logs, I was in hurry...


From the result, I think if `stream-http` run in the `fetch` mode, `ipfs.pin.ls()` functions can be called from ServiceWorker. Could you set break point here and check what mode `stream-http` is running in your Firefox?

https://github.com/jhiesey/stream-http/blob/718f5127ec970e91ea4c323c2491efdffb22a1c9/lib/request.js#L10

Hope this helps. 😄

**Comment by koalalorenzo** [comment]
Well, I can't ask the users to enable `ReadableStreaming` :( 
@jhiesey maybe you can help here

**Comment by lidel** [comment]
FYSA [Streaming API is very close to be enabled by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1389628) in Firefox:

> [..] the only blocker (or at least the main one I know of) is [bug 1385890](https://bugzilla.mozilla.org/show_bug.cgi?id=1385890) and Jason's working on it. Hoping to ship soon. 
> – https://bugzilla.mozilla.org/show_bug.cgi?id=1389628#c6

**Comment by alanshaw** [comment]
@koalalorenzo this should now be fixed in ipfs-api@25.0.0 by https://github.com/ipfs/js-ipfs-api/pull/868 please open a new issue if the problem persists

**Comment by alanshaw** [comment]
argh, yes sorry, thanks @hugomrdias

**Comment by koalalorenzo** [comment]
Any update?

**Comment by lidel** [comment]
FYSA streams just got enabled in Firefox Nightly:

> ![2018-12-09--20-54-05](https://user-images.githubusercontent.com/157609/49702075-c88bd780-fbf4-11e8-8c29-40d3e636829f.png)

Refs.

- https://hg.mozilla.org/integration/autoland/rev/b3ccdaea275b
- https://bugzilla.mozilla.org/show_bug.cgi?id=1389628

**Comment by lidel** [comment]
aaaand Firefox 65 just landed in stable channel with support for `ReadableStream`  :tada: 

![2019-01-30--00-36-04](https://user-images.githubusercontent.com/157609/51948025-5468f580-2427-11e9-9cfa-ab2c93684959.png)

@koalalorenzo are you able to re-check with Firefox 65?

**Comment by koalalorenzo** [comment]
I am not able to test again as we decided to implement it in a different way in order to unlock what we were doing on Orion. Sorry :(
