### ISSUE TITLE
File added as directory

### ISSUE THREAD

**Issue by haggins** [ipfs/js-ipfs-api#850]
By adding a file via `readStream` it gets always stored as a directory. Is there another preferred method to stream files from nodejs to IPFS?

```
const fs = require('fs')
const exec = require('child_process').exec
const ipfsAPI = require('ipfs-api')
const ipfs = ipfsAPI();

let stream = fs.createReadStream('ipfs.png')
ipfs.files.add(stream, {pin: false}, function (err, files) {
  if (err) {
    console.error(err)
    return
  }

  let hash = files[0].hash
  console.log(`Hash: ${hash}`)

  // Get the file
  exec(`ipfs cat ${hash} > image.png`, (err, stdout, stderr) => {
    if (err) {
      console.error(err)
      return
    }
    console.log(`ipfs cat ${hash} > image.png:`, stdout)
  })
})
```
**Output:**

> Hash: QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn
> ipfs cat QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn > image.png: 
> Error: this dag node is a directory

**Comment by haggins** [comment]
It works when I use `fs.readFile('ipfs.png', (err, data) => {` instead.

**Comment by r-a-x** [comment]
so in that case it's not a bug and this should be closed.

**Comment by tylermzeller** [comment]
I believe so too.
