### ISSUE TITLE
Add bl module to package.json dependencies

### ISSUE THREAD

**Issue by seungwon-kang** [ipfs/js-ipfs-api#853]
Hi, I'm using ipfs-api (and I don't use js-ipfs) in my electron project.

bl is used in https://github.com/ipfs/js-ipfs-api/blob/master/src/files/cat.js#L6

but in package.json, it is not in dependencies, so error occurs when executing my electron program builded. (Of course, if I add "bl": "^2.0.1" module to package.json dependencies in my project, it works)

Can you add it to package.json?

**Comment by alanshaw** [comment]
Thanks for reporting @seungwon-kang - would you mind sending a PR to fix?

**Comment by seungwon-kang** [comment]
Of course! I sended PR :)
