### ISSUE TITLE
How to encrypt file using a public key before add it to IPFS ?

### ISSUE THREAD

**Issue by maroodb** [ipfs/js-ipfs-api#857]
Is it possible to encrypt a file using a public key before add it to IPFS? 

Example:
Alice want to add file that only Bob can open it. 

Alice encrypt file using Bob pubkey than add it to IPFS.
Bob get the file hash and download the file, than decrypted using its private key.

**Comment by alanshaw** [comment]
You could use tweetnacl.js. See example here: https://github.com/dchest/tweetnacl-js/wiki/Examples

**Comment by maroodb** [comment]
tweetnacl is an external library. I need to encrypt file using public key of the IPFS node.

**Comment by alanshaw** [comment]
> tweetnacl is an external library

yep - is that an issue?

> I need to encrypt file using public key of the IPFS node.

You can get hold of the public key for your node using `(await ipfs.id()).publicKey`

**Comment by maroodb** [comment]
I meant I wont use an external library for encryption, 
I want to use the keys of IPFS for encryption. the question is how to encrypt data using IPFS keys.
