### ISSUE TITLE
Unable to build 

### ISSUE THREAD

**Issue by biko-the-bird** [ipfs/js-ipfs-api#866]
I have installed ipfs-api into my react application and it works fine in development mode however when I try to create a production build I receive the error 
```
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/ipfs-api/src/utils/module-config.js:7

Read more here: http://bit.ly/2tRViJ9
```
The read more link says that I need to update react-scripts which doesn't even seem to be in the ipfs-api dependencies. (I tried updating it anyways to no avail.) 

I've also tried updating ipfs-api. Nothing has produced any progress. Is this a problem with ipfs as the output above indicates or something else?

**Comment by biko-the-bird** [comment]
This issue was not related to ipfs-api

**Comment by johhonn** [comment]
@biko-the-bird  I am having this same issue. What was causing it in you case?

**Comment by biko-the-bird** [comment]
@johnonn i tried a whole bunch of stuff including:
-manually delete the js-ipfs-api module
-scour stackoverflow for a similar build pack configuration and keep tweaking it until it worked if you’d like I can upload the project I was working on for you to look through?

**Comment by johhonn** [comment]
I ended up switching to to ipfs-mini which gave me the same functionality and I was able to build my project with no issues.I would be interested in seeing you project though. I am trying to better understand webpack and react build configurations.
