### ISSUE TITLE
Upgrade node-ipfs-api to understand ndjson

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs-api#87]
Waiting for 0.3.9 release //cc @whyrusleeping

**Comment by jbenet** [comment]
I believe I merged the relevant PR. Anything else for tonight @whyrusleeping?



—

**Comment by diasdavid** [comment]
rad, let's get 0.3.9 then :)

**Comment by diasdavid** [comment]
Related https://github.com/ipfs/node-ipfs-api/issues/86

**Comment by diasdavid** [comment]
Following https://github.com/ipfs/go-ipfs/issues/1906#issuecomment-151893375

**Comment by diasdavid** [comment]
0.3.9 compatible! streams and everything 🚀
