### ISSUE TITLE
Handle gulp not properly exiting, it looks like this is a bug in node-ipfs-clt

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-ipfs-api#88]
For ref: https://github.com/ipfs/node-ipfs-api/blob/solid-tests/gulpfile.js#L14-L19

**Comment by VictorBjelkholm** [comment]
Feels like this is probably related to https://github.com/ipfs/node-ipfsd-ctl/issues/19

**Comment by diasdavid** [comment]
@Dignifiedquire fixed this :) thank you!
